//
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const ON_HIDE_LOADER = 'ON_HIDE_LOADER';
export const ON_SHOW_LOADER = 'ON_SHOW_LOADER';
//
//
// /**
//  * App Redux Action Types  ---  Member
//  */
//
//
// // store
//
//
// export const GET_STORES = 'GET_STORES';
// export const GET_STORES_SUCCESS = 'GET_STORE_SUCCESS';
// export const OPEN_ADD_NEW_STORE_MODEL = 'OPEN_ADD_NEW_STORE_MODEL';
// export const CLOSE_ADD_NEW_STORE_MODEL = 'CLOSE_ADD_NEW_STORE_MODEL';
// export const OPEN_ADD_NEW_STORE_MODEL_SUCCESS = 'OPEN_ADD_NEW_STORE_MODEL_SUCCESS';
// export const OPEN_EDIT_STORE_MODEL = 'OPEN_EDIT_STORE_MODEL';
// export const OPEN_EDIT_STORE_MODEL_SUCCESS = 'OPEN_EDIT_STORE_MODEL_SUCCESS';
// export const OPEN_VIEW_STORE_MODEL = 'OPEN_VIEW_STORE_MODEL';
// export const OPEN_VIEW_STORE_MODEL_SUCCESS = 'OPEN_VIEW_STORE_MODEL_SUCCESS';
// export const CLOSE_VIEW_STORE_MODEL = 'CLOSE_VIEW_STORE_MODEL';
// export const SAVE_STORE = 'SAVE_STORE';
// export const SAVE_STORE_SUCCESS = 'SAVE_STORE_SUCCESS';
// export const DELETE_STORE = 'DELETE_STORE';
//
// // store category
//
// export const GET_STORECATEGORYS = 'GET_STORECATEGORYS';
// export const GET_STORECATEGORYS_SUCCESS = 'GET_STORECATEGORYS_SUCCESS';
// export const OPEN_ADD_NEW_STORECATEGORY_MODEL = 'OPEN_ADD_NEW_STORECATEGORY_MODEL';
// export const CLOSE_ADD_NEW_STORECATEGORY_MODEL = 'CLOSE_ADD_NEW_STORECATEGORY_MODEL';
// export const OPEN_ADD_NEW_STORECATEGORY_MODEL_SUCCESS = 'OPEN_ADD_NEW_STORECATEGORY_MODEL_SUCCESS';
// export const OPEN_EDIT_STORECATEGORY_MODEL = 'OPEN_EDIT_STORECATEGORY_MODEL';
// export const OPEN_EDIT_STORECATEGORY_MODEL_SUCCESS = 'OPEN_EDIT_STORECATEGORY_MODEL_SUCCESS';
// export const OPEN_VIEW_STORECATEGORY_MODEL = 'OPEN_VIEW_STORECATEGORY_MODEL';
// export const OPEN_VIEW_STORECATEGORY_MODEL_SUCCESS = 'OPEN_VIEW_STORECATEGORY_MODEL_SUCCESS';
// export const CLOSE_VIEW_STORECATEGORY_MODEL = 'CLOSE_VIEW_STORECATEGORY_MODEL';
// export const SAVE_STORECATEGORY = 'SAVE_STORECATEGORY';
// export const SAVE_STORECATEGORY_SUCCESS = 'SAVE_STORECATEGORY_SUCCESS';
// export const DELETE_STORECATEGORY = 'DELETE_STORECATEGORY';
//
//
//
// // deals
//
//
// export const GET_DEALS = 'GET_DEALS';
// export const GET_DEALS_SUCCESS = 'GET_DEAL_SUCCESS';
// export const OPEN_ADD_NEW_DEAL_MODEL = 'OPEN_ADD_NEW_DEAL_MODEL';
// export const CLOSE_ADD_NEW_DEAL_MODEL = 'CLOSE_ADD_NEW_DEAL_MODEL';
// export const OPEN_ADD_NEW_DEAL_MODEL_SUCCESS = 'OPEN_ADD_NEW_DEAL_MODEL_SUCCESS';
// export const OPEN_EDIT_DEAL_MODEL = 'OPEN_EDIT_DEAL_MODEL';
// export const OPEN_EDIT_DEAL_MODEL_SUCCESS = 'OPEN_EDIT_DEAL_MODEL_SUCCESS';
// export const OPEN_VIEW_DEAL_MODEL = 'OPEN_VIEW_DEAL_MODEL';
// export const OPEN_VIEW_DEAL_MODEL_SUCCESS = 'OPEN_VIEW_DEAL_MODEL_SUCCESS';
// export const CLOSE_VIEW_DEAL_MODEL = 'CLOSE_VIEW_DEAL_MODEL';
// export const SAVE_DEAL = 'SAVE_DEAL';
// export const SAVE_DEAL_SUCCESS = 'SAVE_DEAL_SUCCESS';
// export const DELETE_DEAL = 'DELETE_DEAL';
//
// // Deal Type
//
// export const GET_DEALTYPES = 'GET_DEALTYPES';
// export const GET_DEALTYPES_SUCCESS = 'GET_DEALTYPES_SUCCESS';
// export const OPEN_ADD_NEW_DEALTYPE_MODEL = 'OPEN_ADD_NEW_DEALTYPE_MODEL';
// export const CLOSE_ADD_NEW_DEALTYPE_MODEL = 'CLOSE_ADD_NEW_DEALTYPE_MODEL';
// export const OPEN_ADD_NEW_DEALTYPE_MODEL_SUCCESS = 'OPEN_ADD_NEW_DEALTYPE_MODEL_SUCCESS';
// export const OPEN_EDIT_DEALTYPE_MODEL = 'OPEN_EDIT_DEALTYPE_MODEL';
// export const OPEN_EDIT_DEALTYPE_MODEL_SUCCESS = 'OPEN_EDIT_DEALTYPE_MODEL_SUCCESS';
// export const OPEN_VIEW_DEALTYPE_MODEL = 'OPEN_VIEW_DEALTYPE_MODEL';
// export const OPEN_VIEW_DEALTYPE_MODEL_SUCCESS = 'OPEN_VIEW_DEALTYPE_MODEL_SUCCESS';
// export const CLOSE_VIEW_DEALTYPE_MODEL = 'CLOSE_VIEW_DEALTYPE_MODEL';
// export const SAVE_DEALTYPE = 'SAVE_DEALTYPE';
// export const SAVE_DEALTYPE_SUCCESS = 'SAVE_DEALTYPE_SUCCESS';
// export const DELETE_DEALTYPE = 'DELETE_DEALTYPE';



export const GET_GAMES = 'GET_GAMES';
export const GET_GAMES_SUCCESS = 'GET_GAME_SUCCESS';
export const OPEN_ADD_NEW_GAME_MODEL = 'OPEN_ADD_NEW_GAME_MODEL';
export const CLOSE_ADD_NEW_GAME_MODEL = 'CLOSE_ADD_NEW_GAME_MODEL';
export const OPEN_ADD_NEW_GAME_MODEL_SUCCESS = 'OPEN_ADD_NEW_GAME_MODEL_SUCCESS';
export const OPEN_EDIT_GAME_MODEL = 'OPEN_EDIT_GAME_MODEL';
export const OPEN_EDIT_GAME_MODEL_SUCCESS = 'OPEN_EDIT_GAME_MODEL_SUCCESS';
export const OPEN_VIEW_GAME_MODEL = 'OPEN_VIEW_GAME_MODEL';
export const OPEN_VIEW_GAME_MODEL_SUCCESS = 'OPEN_VIEW_GAME_MODEL_SUCCESS';
export const CLOSE_VIEW_GAME_MODEL = 'CLOSE_VIEW_GAME_MODEL';
export const SAVE_GAME = 'SAVE_GAME';
export const SAVE_GAME_SUCCESS = 'SAVE_GAME_SUCCESS';
export const DELETE_GAME = 'DELETE_GAME';
//
//

export const GET_BOOKTICKETS = 'GET_BOOKTICKETS';
export const GET_BOOKTICKETS_SUCCESS = 'GET_BOOKTICKET_SUCCESS';
export const OPEN_ADD_NEW_BOOKTICKET_MODEL = 'OPEN_ADD_NEW_BOOKTICKET_MODEL';
export const CLOSE_ADD_NEW_BOOKTICKET_MODEL = 'CLOSE_ADD_NEW_BOOKTICKET_MODEL';
export const OPEN_ADD_NEW_BOOKTICKET_MODEL_SUCCESS = 'OPEN_ADD_NEW_BOOKTICKET_MODEL_SUCCESS';
export const OPEN_EDIT_BOOKTICKET_MODEL = 'OPEN_EDIT_BOOKTICKET_MODEL';
export const OPEN_EDIT_BOOKTICKET_MODEL_SUCCESS = 'OPEN_EDIT_BOOKTICKET_MODEL_SUCCESS';
export const OPEN_VIEW_BOOKTICKET_MODEL = 'OPEN_VIEW_BOOKTICKET_MODEL';
export const OPEN_VIEW_BOOKTICKET_MODEL_SUCCESS = 'OPEN_VIEW_BOOKTICKET_MODEL_SUCCESS';
export const CLOSE_VIEW_BOOKTICKET_MODEL = 'CLOSE_VIEW_BOOKTICKET_MODEL';
export const SAVE_BOOKTICKET = 'SAVE_BOOKTICKET';
export const SAVE_BOOKTICKET_SUCCESS = 'SAVE_BOOKTICKET_SUCCESS';
export const DELETE_BOOKTICKET = 'DELETE_BOOKTICKET';
export const DELETE_BOOKTICKET_SUCCESS = 'DELETE_BOOKTICKET_SUCCESS';



//
//membership
export const GET_MEMBER_PROFILE = 'GET_MEMBER_PROFILE';
export const GET_MEMBER_PROFILE_SUCCESS = 'GET_MEMBER_PROFILE_SUCCESS';
//
// export const MEMBER_GET_SERVICE_HIT_DETAIL = 'MEMBER_GET_SERVICE_HIT_DETAIL';
// export const MEMBER_GET_SERVICE_HIT_DETAIL_SUCCESS = 'MEMBER_GET_SERVICE_HIT_DETAIL_SUCCESS';
// export const MEMBER_ON_DELETE_ITEM_FROM_CART = 'MEMBER_ON_DELETE_ITEM_FROM_CART';
// export const MEMBER_ON_ADD_ITEM_TO_CART = 'MEMBER_ON_ADD_ITEM_TO_CART';
// export const MEMBER_ON_DATE_CHANGE = 'MEMBER_ON_DATE_CHANGE';
// export const MEMBER_ON_CLASS_CHANGE = 'MEMBER_ON_CLASS_CHANGE';
// export const MEMBER_CART_EMPTY = 'MEMBER_CART_EMPTY';
// export const SAVE_MEMBER_SUBSCRIPTION_DETAILS = 'SAVE_MEMBER_SUBSCRIPTION_DETAILS';
// export const SAVE_MEMBER_SUBSCRIPTION_DETAILS_SUCCESS = 'SAVE_MEMBER_SUBSCRIPTION_DETAILS_SUCCESS';
// export const MEMBER_CHECKFOR_ACTIVE_CLASS = 'MEMBER_CHECKFOR_ACTIVE_CLASS';
// export const MEMBER_CHECKFOR_ACTIVE_CLASS_SUCCESS = 'MEMBER_CHECKFOR_ACTIVE_CLASS_SUCCESS';
// export const CLOSE_MEMBER_BUYSERVICE_REDIRECT_CONFIRMATIONDIALOG = 'CLOSE_MEMBER_BUYSERVICE_REDIRECT_CONFIRMATIONDIALOG';
// export const SAVE_MEMBER_CLASS_BOOKING = 'SAVE_MEMBER_CLASS_BOOKING';
// export const SAVE_MEMBER_CLASS_BOOKING_SUCCESS = 'SAVE_MEMBER_CLASS_BOOKING_SUCCESS';
// export const CLOSE_MEMBER_CLASS_BOOKING_DIALOG = 'CLOSE_MEMBER_CLASS_BOOKING_DIALOG';
// export const MEMBER_DELETE_CLASS_BOOKED = 'MEMBER_DELETE_CLASS_BOOKED';
// export const MEMBER_DELETE_CLASS_BOOKED_SUCCESS = 'MEMBER_DELETE_CLASS_BOOKED_SUCCESS';
//
// //member disclaimer
// export const OPEN_MEMBER_DISCLAIMER_MODEL = 'OPEN_MEMBER_DISCLAIMER_MODEL';
// export const OPEN_MEMBER_DISCLAIMER_MODEL_SUCCESS = 'OPEN_MEMBER_DISCLAIMER_MODEL_SUCCESS';
// export const CLOSE_MEMBER_DISCLAIMER_MODEL = 'CLOSE_MEMBER_DISCLAIMER_MODEL';
// export const SAVE_MEMBER_DISCLAIMER = 'SAVE_MEMBER_DISCLAIMER';
// export const SAVE_MEMBER_DISCLAIMER_SUCCESS = 'SAVE_MEMBER_DISCLAIMER_SUCCESS';
// export const GET_MEMBER_DISCLAIMER_SAVED_FORM = 'GET_MEMBER_DISCLAIMER_SAVED_FORM';
// export const GET_MEMBER_DISCLAIMER_SAVED_FORM_SUCCESS = 'GET_MEMBER_DISCLAIMER_SAVED_FORM_SUCCESS';
//
// //covid19 member disclaimer
//
// export const OPEN_MEMBER_COVID19DISCLAIMER_MODEL = 'OPEN_MEMBER_COVID19DISCLAIMER_MODEL';
// export const OPEN_MEMBER_COVID19DISCLAIMER_MODEL_SUCCESS = 'OPEN_MEMBER_COVID19DISCLAIMER_MODEL_SUCCESS';
// export const CLOSE_MEMBER_COVID19DISCLAIMER_MODEL = 'CLOSE_MEMBER_COVID19DISCLAIMER_MODEL';
// export const SAVE_MEMBER_COVID19DISCLAIMER = 'SAVE_MEMBER_COVID19DISCLAIMER';
// export const SAVE_MEMBER_COVID19DISCLAIMER_SUCCESS = 'SAVE_MEMBER_COVID19DISCLAIMER_SUCCESS';
//
//
// export const GET_MEMBER_WORKOUT_SCHEDULE = 'GET_MEMBER_WORKOUT_SCHEDULE';
// export const GET_MEMBER_WORKOUT_SCHEDULE_SUCCESS = 'GET_MEMBER_WORKOUT_SCHEDULE_SUCCESS';
// export const OPEN_MEMBER_VIEW_WORKOUT_SCHEDULE_MODEL = 'OPEN_MEMBER_VIEW_WORKOUT_SCHEDULE_MODEL';
// export const OPEN_MEMBER_VIEW_WORKOUT_SCHEDULE_MODEL_SUCCESS = 'OPEN_MEMBER_VIEW_WORKOUT_SCHEDULE_MODEL_SUCCESS';
// export const CLOSE_MEMBER_VIEW_WORKOUT_SCHEDULE_MODEL = 'CLOSE_MEMBER_VIEW_WORKOUT_SCHEDULE_MODEL';
// export const SAVE_MEMBER_PHASE = 'SAVE_MEMBER_PHASE';
// export const SAVE_MEMBER_PHASE_SUCCESS = 'SAVE_MEMBER_PHASE_SUCCESS';
//
//
// export const MEMBER_SAVE_CHANGE_PASSWORD = 'MEMBER_SAVE_CHANGE_PASSWORD';
// export const MEMBER_SAVE_CHANGE_PASSWORD_SUCCESS = 'MEMBER_SAVE_CHANGE_PASSWORD_SUCCESS';
//
// export const GET_MEMBER_WORKOUT_ROUTINE = 'GET_MEMBER_WORKOUT_ROUTINE';
// export const GET_MEMBER_WORKOUT_ROUTINE_SUCCESS = 'GET_MEMBER_WORKOUT_ROUTINE_SUCCESS';
// export const OPEN_MEMBER_ADD_NEW_WORKOUT_ROUTINE_MODEL = 'OPEN_MEMBER_ADD_NEW_WORKOUT_ROUTINE_MODEL';
// export const CLOSE_MEMBER_ADD_NEW_WORKOUT_ROUTINE_MODEL = 'CLOSE_MEMBER_ADD_NEW_WORKOUT_ROUTINE_MODEL';
// export const SAVE_MEMBER_WORKOUT_ROUTINE = 'SAVE_MEMBER_WORKOUT_ROUTINE';
// export const SAVE_MEMBER_WORKOUT_ROUTINE_SUCCESS = 'SAVE_MEMBER_WORKOUT_ROUTINE_SUCCESS';
// export const OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_MODEL = 'OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_MODEL';
// export const OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_MODEL_SUCCESS = 'OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_MODEL_SUCCESS';
// export const OPEN_MEMBER_VIEW_WORKOUT_ROUTINE_MODEL = 'OPEN_MEMBER_VIEW_WORKOUT_ROUTINE_MODEL';
// export const OPEN_MEMBER_VIEW_WORKOUT_ROUTINE_MODEL_SUCCESS = 'OPEN_MEMBER_VIEW_WORKOUT_ROUTINE_MODEL_SUCCESS';
// export const CLOSE_MEMBER_VIEW_WORKOUT_ROUTINE_MODEL = 'CLOSE_MEMBER_VIEW_WORKOUT_ROUTINE_MODEL';
// export const DELETE_MEMBER_WORKOUT_ROUTINE = 'DELETE_MEMBER_WORKOUT_ROUTINE';
// export const SAVE_MEMBER_WORKOUT_ROUTINE_ACTIVE = 'SAVE_MEMBER_WORKOUT_ROUTINE_ACTIVE';
// export const SAVE_MEMBER_WORKOUT_ROUTINE_ACTIVE_SUCCESS = 'SAVE_MEMBER_WORKOUT_ROUTINE_ACTIVE_SUCCESS';
//
// // workout routine day workout
// export const OPEN_MEMBER_ADD_NEW_WORKOUT_ROUTINE_DAY_MODEL = 'OPEN_MEMBER_ADD_NEW_WORKOUT_ROUTINE_DAY_MODEL';
// export const CLOSE_MEMBER_ADD_NEW_WORKOUT_ROUTINE_DAY_MODEL = 'CLOSE_MEMBER_ADD_NEW_WORKOUT_ROUTINE_DAY_MODEL';
// export const SAVE_MEMBER_WORKOUT_ROUTINE_DAY = 'SAVE_MEMBER_WORKOUT_ROUTINE_DAY';
// export const SAVE_MEMBER_WORKOUT_ROUTINE_DAY_SUCCESS = 'SAVE_MEMBER_WORKOUT_ROUTINE_DAY_SUCCESS';
// export const OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_DAY_MODEL = 'OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_DAY_MODEL';
// export const OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_DAY_MODEL_SUCCESS = 'OPEN_MEMBER_EDIT_WORKOUT_ROUTINE_DAY_MODEL_SUCCESS';
// export const DELETE_MEMBER_WORKOUT_ROUTINE_DAY = 'DELETE_MEMBER_WORKOUT_ROUTINE_DAY';
// export const SAVE_MEMBER_WORKOUTEXERCISE = 'SAVE_MEMBER_WORKOUTEXERCISE';
// export const SAVE_MEMBER_WORKOUTEXERCISE_SUCCESS = 'SAVE_MEMBER_WORKOUTEXERCISE_SUCCESS';
//
// //Body Progress
// export const OPEN_MEMBER_ADD_NEW_BODY_PROGRESS_MODEL = 'OPEN_MEMBER_ADD_NEW_BODY_PROGRESS_MODEL';
// export const CLOSE_MEMBER_ADD_NEW_BODY_PROGRESS_MODEL = 'CLOSE_MEMBER_ADD_NEW_BODY_PROGRESS_MODEL';
// export const GET_BODY_PROGRESS = 'GET_BODY_PROGRESS';
// export const GET_BODY_PROGRESS_SUCCESS = 'GET_BODY_PROGRESS_SUCCESS';
// export const SAVE_BODY_MEASUREMENT = 'SAVE_BODY_MEASUREMENT';
// export const SAVE_BODY_MEASUREMENT_SUCCESS = 'SAVE_BODY_MEASUREMENT_SUCCESS';
// export const OPEN_MEMBER_VIEW_BODY_PROGRESS_CHART_MODEL = 'OPEN_MEMBER_VIEW_BODY_PROGRESS_CHART_MODEL';
// export const CLOSE_MEMBER_VIEW_BODY_PROGRESS_CHART_MODEL = 'CLOSE_MEMBER_VIEW_BODY_PROGRESS_CHART_MODEL';
// export const OPEN_MEMBER_VIEW_INBODY_PROGRESS_CHART_MODEL = 'OPEN_MEMBER_VIEW_INBODY_PROGRESS_CHART_MODEL';
// export const CLOSE_MEMBER_VIEW_INBODY_PROGRESS_CHART_MODEL = 'CLOSE_MEMBER_VIEW_INBODY_PROGRESS_CHART_MODEL';
//
// export const OPEN_MEMBER_ADD_EXERCISE_LOG_MODEL = 'OPEN_MEMBER_ADD_EXERCISE_LOG_MODEL';
// export const SAVE_MEMBER_WORKOUT_SESSION_SUCCESS = 'SAVE_MEMBER_WORKOUT_SESSION_SUCCESS';
// export const CLOSE_MEMBER_ADD_EXERCISE_LOG_MODEL = 'CLOSE_MEMBER_ADD_EXERCISE_LOG_MODEL';
// export const SAVE_MEMBER_EXERCISE_LOG = 'SAVE_MEMBER_EXERCISE_LOG';
// export const SAVE_MEMBER_EXERCISE_LOG_SUCCESS = 'SAVE_MEMBER_EXERCISE_LOG_SUCCESS';
// export const OPEN_MEMBER_ADD_NEW_EXERCISE_FEEDBACK_MODEL = 'OPEN_MEMBER_ADD_NEW_EXERCISE_FEEDBACK_MODEL';
// export const CLOSE_MEMBER_ADD_NEW_EXERCISE_FEEDBACK_MODEL = 'CLOSE_MEMBER_ADD_NEW_EXERCISE_FEEDBACK_MODEL';
// export const CHANGE_VOICE_FEEDBACK = 'CHANGE_VOICE_FEEDBACK';
// export const CHANGE_INTERVAL_VIBRATION = 'CHANGE_INTERVAL_VIBRATION';
// export const SAVE_MEMBER_EXERCISE_FEEDBACK = 'SAVE_MEMBER_EXERCISE_FEEDBACK';
// export const SAVE_MEMBER_EXERCISE_LOG_COPY = 'SAVE_MEMBER_EXERCISE_LOG_COPY';
// export const SAVE_MEMBER_EXERCISE_LOG_COPY_SUCCESS = 'SAVE_MEMBER_EXERCISE_LOG_COPY_SUCCESS';
//
//
// export const END_MEMBER_WORKOUT_SESSION = 'END_MEMBER_WORKOUT_SESSION';
// export const END_MEMBER_WORKOUT_SESSION_SUCCESS = 'END_MEMBER_WORKOUT_SESSION_SUCCESS';
//
export const SAVE_MEMBER_THEME = 'SAVE_MEMBER_THEME';
export const SAVE_MEMBER_THEME_SUCCESS = 'SAVE_MEMBER_THEME_SUCCESS';

// // member water log
// export const SAVE_MEMBER_WATER_GOAL = 'SAVE_MEMBER_WATER_GOAL';
// export const SAVE_MEMBER_WATER_LOG = 'SAVE_MEMBER_WATER_LOG';
// export const OPEN_MEMBER_VIEW_WATER_LOG_MODEL = 'OPEN_MEMBER_VIEW_WATER_LOG_MODEL';
// export const OPEN_MEMBER_VIEW_WATER_LOG_MODEL_SUCCESS = 'OPEN_MEMBER_VIEW_WATER_LOG_MODEL_SUCCESS';
// export const CLOSE_MEMBER_VIEW_WATER_LOG_MODEL = 'CLOSE_MEMBER_VIEW_WATER_LOG_MODEL';
// export const DELETE_MEMBER_WATER_LOG = 'DELETE_MEMBER_WATER_LOG';
// export const GET_MEMBER_TODAYCONSUMEDWATER = 'GET_MEMBER_TODAYCONSUMEDWATER';
// export const GET_MEMBER_TODAYCONSUMEDWATER_SUCCESS = 'GET_MEMBER_TODAYCONSUMEDWATER_SUCCESS';
//
// // member diet routine
// export const OPEN_MEMBER_ADD_NEW_DIET_ROUTINE_MODEL = 'OPEN_MEMBER_ADD_NEW_DIET_ROUTINE_MODEL';
// export const CLOSE_MEMBER_ADD_NEW_DIET_ROUTINE_MODEL = 'CLOSE_MEMBER_ADD_NEW_DIET_ROUTINE_MODEL';
// export const SAVE_MEMBER_DIET_ROUTINE = 'SAVE_MEMBER_DIET_ROUTINE';
// export const SAVE_MEMBER_DIET_ROUTINE_SUCCESS = 'SAVE_MEMBER_DIET_ROUTINE_SUCCESS';
// export const GET_MEMBER_DIET_ROUTINE = 'GET_MEMBER_DIET_ROUTINE';
// export const GET_MEMBER_DIET_ROUTINE_SUCCESS = 'GET_MEMBER_DIET_ROUTINE_SUCCESS';
// export const OPEN_MEMBER_EDIT_DIET_ROUTINE_MODEL = 'OPEN_MEMBER_EDIT_DIET_ROUTINE_MODEL';
// export const OPEN_MEMBER_EDIT_DIET_ROUTINE_MODEL_SUCCESS = 'OPEN_MEMBER_EDIT_DIET_ROUTINE_MODEL_SUCCESS';
// export const OPEN_MEMBER_VIEW_DIET_ROUTINE_MODEL = 'OPEN_MEMBER_VIEW_DIET_ROUTINE_MODEL';
// export const OPEN_MEMBER_VIEW_DIET_ROUTINE_MODEL_SUCCESS = 'OPEN_MEMBER_VIEW_DIET_ROUTINE_MODEL_SUCCESS';
// export const CLOSE_MEMBER_VIEW_DIET_ROUTINE_MODEL = 'CLOSE_MEMBER_VIEW_DIET_ROUTINE_MODEL';
// export const DELETE_MEMBER_DIET_ROUTINE = 'DELETE_MEMBER_DIET_ROUTINE';
// export const SAVE_MEMBER_DIET_ROUTINE_ACTIVE = 'SAVE_MEMBER_DIET_ROUTINE_ACTIVE';
// export const SAVE_MEMBER_DIET_ROUTINE_ACTIVE_SUCCESS = 'SAVE_MEMBER_DIET_ROUTINE_ACTIVE_SUCCESS';
//
//
// // member allocate diet
// export const SAVE_MEMBER_DIET_PHASE = 'SAVE_MEMBER_DIET_PHASE';
// export const SAVE_MEMBER_DIET_PHASE_SUCCESS = 'SAVE_MEMBER_DIET_PHASE_SUCCESS';
// export const GET_MEMBER_ALLOCATEDIETS = 'GET_MEMBER_ALLOCATEDIETS';
// export const GET_MEMBER_ALLOCATEDIET_SUCCESS = 'GET_MEMBER_ALLOCATEDIET_SUCCESS';
// export const OPEN_MEMBER_VIEW_ALLOCATEDIETS_MODEL = 'OPEN_MEMBER_VIEW_ALLOCATEDIETS_MODEL';
// export const OPEN_MEMBER_VIEW_ALLOCATEDIETS_MODEL_SUCCESS = 'OPEN_MEMBER_VIEW_ALLOCATEDIETS_MODEL_SUCCESS';
// export const CLOSE_MEMBER_VIEW_ALLOCATEDIETS_MODEL = 'CLOSE_MEMBER_VIEW_ALLOCATEDIETS_MODEL';
//
// //member diet log
// export const MEMBER_ACTIVE_DIET_ROUTINE = 'MEMBER_ACTIVE_DIET_ROUTINE';
// export const MEMBER_ACTIVE_DIET_ROUTINE_SUCCESS = 'MEMBER_ACTIVE_DIET_ROUTINE_SUCCESS';
// export const SAVE_MEMBER_DIET_LOG = 'SAVE_MEMBER_DIET_LOG';
// export const SAVE_MEMBER_DIET_LOG_SUCCESS = 'SAVE_MEMBER_DIET_LOG_SUCCESS';
// export const DELETE_MEMBER_DIET_LOG = 'DELETE_MEMBER_DIET_LOG';
// export const OPEN_MEMBER_DIET_LOG_MODEL = 'OPEN_MEMBER_DIET_LOG_MODEL';
// export const CLOSE_MEMBER_DIET_LOG_MODEL = 'CLOSE_MEMBER_DIET_LOG_MODEL';
// export const VIEW_MEMBER_DIET_LOG = 'VIEW_MEMBER_DIET_LOG';
// export const VIEW_MEMBER_DIET_LOG_SUCCESS = 'VIEW_MEMBER_DIET_LOG_SUCCESS';
//
// // unit
export const OPEN_MEMBER_UNIT_MODEL = 'OPEN_MEMBER_UNIT_MODEL';
export const CLOSE_MEMBER_UNIT_MODEL = 'CLOSE_MEMBER_UNIT_MODEL';
export const CHANGE_WEIGHT_UNIT = 'CHANGE_WEIGHT_UNIT';
export const CHANGE_DISTANCE_UNIT = 'CHANGE_DISTANCE_UNIT';
export const CHANGE_LENGTH_UNIT = 'CHANGE_LENGTH_UNIT';
export const CHANGE_TEMPERATURE_UNIT = 'CHANGE_TEMPERATURE_UNIT';

export const SAVE_MEMBER_UNIT = 'SAVE_MEMBER_UNIT';
export const SAVE_USER_UNIT= 'SAVE_USER_UNIT';
export const OPEN_ADD_NEW_TAX_MODEL = 'OPEN_ADD_NEW_TAX_MODEL';
export const OPEN_ADD_NEW_TAX_MODEL_SUCCESS = 'OPEN_ADD_NEW_TAX_MODEL_SUCCESS';
export const CLOSE_ADD_NEW_TAX_MODEL = 'CLOSE_ADD_NEW_TAX_MODEL';
export const SAVE_CLIENT_TAX = 'SAVE_CLIENT_TAX';
export const SAVE_CLIENT_TAX_SUCCESS = 'SAVE_CLIENT_TAX_SUCCESS';
export const GET_CLIENT_TAX = 'GET_CLIENT_TAX';
export const GET_CLIENT_TAX_SUCCESS = 'GET_CLIENT_TAX_SUCCESS';
export const SAVE_CLIENT_TAX_CONFIGURATION = 'SAVE_CLIENT_TAX_CONFIGURATION';
export const OPEN_VIEW_CLIENT_TAX_MODEL = 'OPEN_VIEW_CLIENT_TAX_MODEL';
export const OPEN_VIEW_CLIENT_TAX_MODEL_SUCCESS = 'OPEN_VIEW_CLIENT_TAX_MODEL_SUCCESS';
export const CLOSE_VIEW_CLIENT_TAX_MODEL = 'CLOSE_VIEW_CLIENT_TAX_MODEL';
export const DELETE_CLIENT_TAX = 'DELETE_CLIENT_TAX';
export const OPEN_ADD_NEW_TAX_CODE_CATEGORY_MODEL = 'OPEN_ADD_NEW_TAX_CODE_CATEGORY_MODEL';
export const OPEN_ADD_NEW_TAX_CODE_CATEGORY_MODEL_SUCCESS = 'OPEN_ADD_NEW_TAX_CODE_CATEGORY_MODEL_SUCCESS';
export const CLOSE_ADD_NEW_TAX_CODE_CATEGORY_MODEL = 'CLOSE_ADD_NEW_TAX_CODE_CATEGORY_MODEL';
export const SAVE_TAX_CODE_CATEGORY = 'SAVE_TAX_CODE_CATEGORY';
export const SAVE_TAX_CODE_CATEGORY_SUCCESS = 'SAVE_TAX_CODE_CATEGORY_SUCCESS';
export const GET_TAX_CODE_CATEGORY = 'GET_TAX_CODE_CATEGORY';
export const GET_TAX_CODE_CATEGORY_SUCCESS = 'GET_TAX_CODE_CATEGORY_SUCCESS';
export const OPEN_VIEW_TAX_CODE_CATEGORY_MODEL = 'OPEN_VIEW_TAX_CODE_CATEGORY_MODEL';
export const OPEN_VIEW_TAX_CODE_CATEGORY_MODEL_SUCCESS = 'OPEN_VIEW_TAX_CODE_CATEGORY_MODEL_SUCCESS';
export const CLOSE_VIEW_TAX_CODE_CATEGORY_MODEL = 'CLOSE_VIEW_TAX_CODE_CATEGORY_MODEL';
export const DELETE_TAX_CODE_CATEGORY = 'DELETE_TAX_CODE_CATEGORY';
export const SAVE_CLIENT_BIOMETRIC_CONFIGURATION = 'SAVE_CLIENT_BIOMETRIC_CONFIGURATION';
export const OPEN_ADD_NEW_BIOMETRIC_MODEL = 'OPEN_ADD_NEW_BIOMETRIC_MODEL';
export const CLOSE_ADD_NEW_BIOMETRIC_MODEL = 'CLOSE_ADD_NEW_BIOMETRIC_MODEL';
export const SAVE_CLIENT_BIOMETRIC = 'SAVE_CLIENT_BIOMETRIC';
export const SAVE_CLIENT_BIOMETRIC_SUCCESS = 'SAVE_CLIENT_BIOMETRIC_SUCCESS';
export const GET_CLIENT_BIOMETRIC = 'GET_CLIENT_BIOMETRIC';
export const GET_CLIENT_BIOMETRIC_SUCCESS = 'GET_CLIENT_BIOMETRIC_SUCCESS';
export const OPEN_VIEW_CLIENT_BIOMETRIC_MODEL = 'OPEN_VIEW_CLIENT_BIOMETRIC_MODEL';
export const OPEN_VIEW_CLIENT_BIOMETRIC_MODEL_SUCCESS = 'OPEN_VIEW_CLIENT_BIOMETRIC_MODEL_SUCCESS';
export const CLOSE_VIEW_CLIENT_BIOMETRIC_MODEL = 'CLOSE_VIEW_CLIENT_BIOMETRIC_MODEL';

// // member attended SAVE_SESSIONWEIGHT
//
// export const GET_MEMBER_ATTENDED_SESSION = 'GET_MEMBER_ATTENDED_SESSION';
// export const GET_MEMBER_ATTENDED_SESSION_SUCCESS = 'GET_MEMBER_ATTENDED_SESSION_SUCCESS';
// export const CONFIRM_MEMBER_ATTENDED_SESSION = 'CONFIRM_MEMBER_ATTENDED_SESSION';
// export const SAVE_MEMBER_ATTENDED_PT_SESSION_FEEDBACK = 'SAVE_MEMBER_ATTENDED_PT_SESSION_FEEDBACK';
// export const SAVE_MEMBER_ATTENDED_PT_SESSION_FEEDBACK_SUCCESS = 'SAVE_MEMBER_ATTENDED_PT_SESSION_FEEDBACK_SUCCESS';
// export const SAVE_MEMBER_ATTENDED_GS_SESSION_FEEDBACK = 'SAVE_MEMBER_ATTENDED_GS_SESSION_FEEDBACK';
// export const SAVE_MEMBER_ATTENDED_GS_SESSION_FEEDBACK_SUCCESS = 'SAVE_MEMBER_ATTENDED_GS_SESSION_FEEDBACK_SUCCESS';
//
// export const GET_USER_RATING = 'GET_USER_RATING';
// export const GET_USER_RATING_SUCCESS = 'GET_USER_RATING_SUCCESS';
// export const SAVE_USERRATING_FEEDBACK = 'SAVE_USERRATING_FEEDBACK';
// export const SAVE_USERRATING_FEEDBACK_SUCCESS = 'SAVE_USERRATING_FEEDBACK_SUCCESS';
//
// // gym access slot
//
// export const SAVE_MEMBER_GYMACCESSSLOT = 'SAVE_MEMBER_GYMACCESSSLOT';
// export const SAVE_MEMBER_GYMACCESSSLOT_SUCCESS = 'SAVE_MEMBER_GYMACCESSSLOT_SUCCESS';
// export const DELETE_MEMBER_GYM_ACCESS_SLOT = 'DELETE_MEMBER_GYM_ACCESS_SLOT';
// export const DELETE_MEMBER_GYM_ACCESS_SLOT_SUCCESS = 'DELETE_MEMBER_GYM_ACCESS_SLOT_SUCCESS';
//
// // pt slot
//
// export const SAVE_MEMBER_PTSLOT = 'SAVE_MEMBER_PTSLOT';
// export const SAVE_MEMBER_PTSLOT_SUCCESS = 'SAVE_MEMBER_PTSLOT_SUCCESS';
// export const DELETE_MEMBER_PT_SLOT = 'DELETE_MEMBER_PT_SLOT';
// export const DELETE_MEMBER_PT_SLOT_SUCCESS = 'DELETE_MEMBER_PT_SLOT_SUCCESS';
// export const SAVE_MEMBER_ONLINEATTENDANCE = 'SAVE_MEMBER_ONLINEATTENDANCE';
//
// //pt rooms
//
// export const ADD_ROOM = 'ADD_ROOM';
// export const SET_VIDEO = 'SET_VIDEO';
// export const SET_AUDIO = 'SET_AUDIO';
//
//
//
// /**
//  * App Redux Action Types
//  */
export const COLLAPSED_SIDEBAR = 'COLLAPSED_SIDEBAR';
export const DARK_MODE = 'DARK_MODE'
export const LIGHT_MODE = 'LIGHT_MODE';
export const BOXED_LAYOUT = 'BOXED_LAYOUT';
export const RTL_LAYOUT = 'RTL_LAYOUT';
export const MINI_SIDEBAR = 'MINI_SIDEBAR';
export const SEARCH_FORM_ENABLE = 'SEARCH_FORM_ENABLE';
export const CHANGE_THEME_COLOR = 'CHANGE_THEME_COLOR';
export const TOGGLE_SIDEBAR_IMAGE = 'TOGGLE_SIDEBAR_IMAGE';
export const SET_SIDEBAR_IMAGE = 'SET_SIDEBAR_IMAGE';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const START_USER_TOUR = 'START_USER_TOUR';
export const STOP_USER_TOUR = 'STOP_USER_TOUR';
export const TOGGLE_DARK_SIDENAV = 'TOGGLE_DARK_SIDENAV';

export const GET_SESSIONTYPE_LIST = 'GET_SESSIONTYPE_LIST';
export const GET_SESSIONTYPE_LIST_SUCCESS = 'GET_SESSIONTYPE_LIST_SUCCESS';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';

export const SAVE_TERMSCONDITION = 'SAVE_TERMSCONDITION';
export const SAVE_TERMSCONDITION_SUCCESS = 'SAVE_TERMSCONDITION_SUCCESS';


export const GET_CLIENT_PROFILE = 'GET_CLIENT_PROFILE';
export const GET_CLIENT_PROFILE_SUCCESS = 'GET_CLIENT_PROFILE_SUCCESS';

export const GET_BRANCH_PROFILE = 'GET_BRANCH_PROFILE';
export const GET_BRANCH_PROFILE_SUCCESS = 'GET_BRANCH_PROFILE_SUCCESS';

export const SAVE_CLIENT_PROFILE = 'SAVE_CLIENT_PROFILE';
export const SAVE_CLIENT_PROFILE_SUCCESS = 'SAVE_CLIENT_PROFILE_SUCCESS';

export const SAVE_CHANGE_PASSWORD = 'SAVE_CHANGE_PASSWORD';
export const SAVE_CHANGE_PASSWORD_SUCCESS = 'SAVE_CHANGE_PASSWORD_SUCCESS';

export const SAVE_USER_THEME = 'SAVE_USER_THEME';
export const SAVE_USER_THEME_SUCCESS = 'SAVE_USER_THEME_SUCCESS';

export const SET_USER_THEME = 'SET_USER_THEME';

// export const SAVE_MEMBER_FEEDBACK = 'SAVE_MEMBER_FEEDBACK';
// export const SAVE_MEMBER_FEEDBACK_SUCCESS = 'SAVE_MEMBER_FEEDBACK_SUCCESS';
// export const GET_MEMBER_FEEDBACKS = 'GET_MEMBER_FEEDBACKS';
// export const GET_MEMBER_FEEDBACKS_SUCCESS = 'GET_MEMBER_FEEDBACKS_SUCCESS';
// export const ON_CHANGE_MEMBER_FEEDBACK_PAGE_TABS = 'ON_CHANGE_MEMBER_FEEDBACK_PAGE_TABS';
// export const VIEW_MEMBER_FEEDBACK_DETAILS = 'VIEW_MEMBER_FEEDBACK_DETAILS';
// export const ON_COMMENT_MEMBER_FEEDBACK = 'ON_COMMENT_MEMBER_FEEDBACK';
// export const ON_COMMENT_MEMBER_FEEDBACK_SUCCESS = 'ON_COMMENT_MEMBER_FEEDBACK_SUCCESS';
// export const REPLY_MEMBER_FEEDBACK = 'REPLY_MEMBER_FEEDBACK';
// export const VIEW_MEMBER_COMMENTS_DETAILS = 'VIEW_MEMBER_COMMENTS_DETAILS';
// export const VIEW_MEMBER_COMMENTS_DETAILS_SUCCESS = 'VIEW_MEMBER_COMMENTS_DETAILS_SUCCESS';
//
export const SAVE_CONFIGURATION = 'SAVE_CONFIGURATION';
export const SAVE_CONFIGURATION_SUCCESS = 'SAVE_CONFIGURATION_SUCCESS';

export const VIEW_CONFIGURATION_DETAIL = 'VIEW_CONFIGURATION_DETAIL';
export const VIEW_CONFIGURATION_DETAIL_SUCCESS = 'VIEW_CONFIGURATION_DETAIL_SUCCESS';

export const SAVE_PAYMENTGATEWAY_CONFIGURATION = 'SAVE_PAYMENTGATEWAY_CONFIGURATION';
export const SAVE_PAYMENTGATEWAY_CONFIGURATION_SUCCESS = 'SAVE_PAYMENTGATEWAY_CONFIGURATION_SUCCESS';

export const SAVE_PAYMENTGATEWAY_CONFIGURATION_STATUS = 'SAVE_PAYMENTGATEWAY_CONFIGURATION_STATUS';
export const SAVE_PAYMENTGATEWAY_CONFIGURATION_STATUS_SUCCESS = 'SAVE_PAYMENTGATEWAY_CONFIGURATION_STATUS_SUCCESS';


export const SAVE_CLIENT_SOCIALMEDIA = 'SAVE_CLIENT_SOCIALMEDIA';

export const ON_CANCEL_ADVANCEBOOKINGOFMEMBER = 'ON_CANCEL_ADVANCEBOOKINGOFMEMBER';

//
// // sidebar
 export const TOGGLE_MENU = 'TOGGLE_MENU';
//
// /**
//
// // Chat App Actions
// export const CHAT_WITH_SELECTED_USER = 'CHAT_WITH_SELECTED_USER';
// export const SEND_MESSAGE_TO_USER = 'SEND_MESSAGE_TO_USER';
// export const UPDATE_USERS_SEARCH = 'UPDATE_USERS_SEARCH';
// export const SEARCH_USERS = 'SEARCH_USERS';
// export const GET_RECENT_CHAT_USERS = 'GET_RECENT_CHAT_USERS';
//
// // Mail App
// export const GET_EMAILS = 'GET_EMAILS';
// export const GET_EMAIL_SUCCESS = 'GET_EMAIL_SUCCESS';
// export const GET_EMAIL_FAILURE = 'GET_EMAIL_FAILURE';
// export const SET_EMAIL_AS_STAR = 'SET_EMAIL_AS_STAR';
// export const READ_EMAIL = 'READ_EMAIL';
// export const HIDE_LOADING_INDICATOR = 'HIDE_LOADING_INDICATOR';
// export const FETCH_EMAILS = 'FETCH_EMAILS';
// export const ON_SELECT_EMAIL = 'ON_SELECT_EMAIL';
// export const UPDATE_EMAIL_SEARCH = 'UPDATE_EMAIL_SEARCH';
// export const SEARCH_EMAIL = 'SEARCH_EMAIL';
// export const ON_DELETE_MAIL = 'ON_DELETE_MAIL';
// export const ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING = 'ON_BACK_PRESS_NAVIGATE_TO_EMAIL_LISTING';
// export const GET_SENT_EMAILS = 'GET_SENT_EMAILS';
// export const GET_INBOX = 'GET_INBOX';
// export const GET_DRAFTS_EMAILS = 'GET_DRAFTS_EMAILS';
// export const GET_SPAM_EMAILS = 'GET_SPAM_EMAILS';
// export const GET_TRASH_EMAILS = 'GET_TRASH_EMAILS';
// export const ON_EMAIL_MOVE_TO_FOLDER = 'ON_EMAIL_MOVE_TO_FOLDER';
// export const SELECT_ALL_EMAILS = 'SELECT_ALL_EMAILS';
// export const UNSELECT_ALL_EMAILS = 'UNSELECT_ALL_EMAILS';
// export const ON_SEND_EMAIL = 'ON_SEND_EMAIL';
// export const EMAIL_SENT_SUCCESSFULLY = 'EMAIL_SENT_SUCCESSFULLY';
// export const FILTER_EMAILS_WITH_LABELS = 'FILTER_EMAILS_WITH_LABELS';
// export const ADD_LABELS_INTO_EMAILS = 'ADD_LABELS_INTO_EMAILS';
//
//
// // ToDo App
// export const GET_TODOS = 'GET_TODOS';
// export const FETCH_TODOS = 'FETCH_TODOS';
// export const ADD_NEW_TASK = 'ADD_NEW_TASK';
// export const ON_SELECT_TODO = 'ON_SELECT_TODO';
// export const ON_BACK_TO_TODOS = 'ON_BACK_TO_TODOS';
// export const MARK_AS_STAR_TODO = 'MARK_AS_STAR_TODO';
// export const DELETE_TODO = 'DELETE_TODO';
// export const ADD_LABELS_INTO_THE_TASK = 'ADD_LABELS_INTO_THE_TASK';
// export const GET_ALL_TODO = 'GET_ALL_TODO';
// export const GET_COMPLETED_TODOS = 'GET_COMPLETED_TODOS';
// export const GET_DELETED_TODOS = 'GET_DELETED_TODOS';
// export const GET_STARRED_TODOS = 'GET_STARRED_TODOS';
// export const GET_FILTER_TODOS = 'GET_FILTER_TODOS';
// export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
// export const COMPLETE_TASK = 'COMPLETE_TASK';
// export const UPDATE_TASK_TITLE = 'UPDATE_TASK_TITLE';
// export const UPDATE_TASK_DESCRIPTION = 'UPDATE_TASK_DESCRIPTION';
// export const CHANGE_TASK_ASSIGNER = 'CHANGE_TASK_ASSIGNER';
// export const ON_CHECK_BOX_TOGGLE_TODO_ITEM = 'ON_CHECK_BOX_TOGGLE_TODO_ITEM';
// export const SELECT_ALL_TODO = 'SELECT_ALL_TODO';
// export const GET_UNSELECTED_ALL_TODO = 'GET_UNSELECTED_ALL_TODO';
// export const SELECT_STARRED_TODO = 'SELECT_STARRED_TODO';
// export const SELECT_UNSTARRED_TODO = 'SELECT_UNSTARRED_TODO';
// export const ON_LABEL_SELECT = 'ON_LABEL_SELECT';
// export const ON_LABEL_MENU_ITEM_SELECT = 'ON_LABEL_MENU_ITEM_SELECT';
// export const UPDATE_SEARCH = 'UPDATE_SEARCH';
// export const SEARCH_TODO = 'SEARCH_TODO';
// export const GET_TODOS_SUCCESS = 'GET_TODOS_SUCCESS';
// export const GET_TODOS_FAILURE = 'GET_TODOS_FAILURE';
//
// */
//
// // Auth Actions
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';
export const LOGIN_FACEBOOK_USER = 'LOGIN_FACEBOOK_USER';
export const LOGIN_GOOGLE_USER = 'LOGIN_GOOGLE_USER';
export const LOGIN_TWITTER_USER = 'LOGIN_TWITTER_USER';
export const LOGIN_GITHUB_USER = 'LOGIN_GITHUB_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
export const SIGNUP_URL = 'SIGNUP_URL';
export const SIGNUP_URL_SUCCESS = 'SIGNUP_URL_SUCCESS';
export const SIGNUP_URL_FAILURE = 'SIGNUP_URL_FAILURE';
export const FORGET_WEBADDRESS = 'FORGET_WEBADDRESS';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
//
// // Feedbacks
// export const GET_FEEDBACKS = 'GET_FEEDBACKS';
// export const GET_FEEDBACKS_SUCCESS = 'GET_FEEDBACKS_SUCCESS';
// export const GET_FEEDBACKS_FAILURE = 'GET_FEEDBACKS_FAILURE';
// export const GET_ALL_FEEDBACKS = 'GET_ALL_FEEDBACKS';
// export const ON_CHANGE_FEEDBACK_PAGE_TABS = 'ON_CHANGE_FEEDBACK_PAGE_TABS';
// export const MAKE_FAVORITE_FEEDBACK = 'MAKE_FAVORITE_FEEDBACK';
// export const ON_DELETE_FEEDBACK = 'ON_DELETE_FEEDBACK';
// export const VIEW_FEEDBACK_DETAILS = 'VIEW_FEEDBACK_DETAILS';
// export const VIEW_COMMENTS_DETAILS = 'VIEW_COMMENTS_DETAILS';
// export const VIEW_COMMENTS_DETAILS_SUCCESS = 'VIEW_COMMENTS_DETAILS_SUCCESS';
// export const ADD_NEW_FEEDBACK = 'ADD_NEW_FEEDBACK';
// export const SHOW_FEEDBACK_LOADING_INDICATOR = 'SHOW_FEEDBACK_LOADING_INDICATOR';
// export const HIDE_FEEDBACK_LOADING_INDICATOR = 'HIDE_FEEDBACK_LOADING_INDICATOR';
// export const NAVIGATE_TO_BACK = 'NAVIGATE_TO_BACK';
// export const REPLY_FEEDBACK = 'REPLY_FEEDBACK';
// export const SEND_REPLY = 'SEND_REPLY';
// export const UPDATE_SEARCH_IDEA = 'UPDATE_SEARCH_IDEA';
// export const ON_SEARCH_IDEA = 'ON_SEARCH_IDEA';
// export const ON_COMMENT_FEEDBACK = 'ON_COMMENT_FEEDBACK';
// export const ON_COMMENT_FEEDBACK_SUCCESS = 'ON_COMMENT_FEEDBACK_SUCCESS';
// export const SAVE_FEEDBACK = 'SAVE_FEEDBACK';
// export const SAVE_FEEDBACK_SUCCESS = 'SAVE_FEEDBACK_SUCCESS';
// export const SAVE_FEEDBACK_STATUS = 'SAVE_FEEDBACK_STATUS';
// export const SAVE_FEEDBACK_STATUS_SUCCESS = 'SAVE_FEEDBACK_STATUS_SUCCESS';
//
// // ecommerce
export const ON_DELETE_ITEM_FROM_CART = 'ON_DELETE_ITEM_FROM_CART';
export const ON_QUANTITY_CHANGE = 'ON_QUANTITY_CHANGE';
export const ON_ADD_ITEM_TO_CART = 'ON_ADD_ITEM_TO_CART';
export const ON_EMPLOYEELIST = 'ON_EMPLOYEELIST';
export const ON_EMPLOYEELIST_SUCCESS = 'ON_EMPLOYEELIST_SUCCESS';
export const ON_EMPLOYEE_CHANGE = 'ON_EMPLOYEE_CHANGE';
export const GET_SERVICE_HIT_DETAIL = 'GET_SERVICE_HIT_DETAIL';
export const GET_SERVICE_HIT_DETAIL_SUCCESS = 'GET_SERVICE_HIT_DETAIL_SUCCESS';
export const ON_DATE_CHANGE = 'ON_DATE_CHANGE';
export const GET_MEMBER_DETAILS = 'GET_MEMBER_DETAILS';
export const GET_MEMBER_DETAILS_SUCCESS = 'GET_MEMBER_DETAILS_SUCCESS';
export const SAVE_MEMBER_DETAIL = 'SAVE_MEMBER_DETAIL';
export const GET_ENQUIRY_DETAILS = 'GET_ENQUIRY_DETAILS';
export const GET_ENQUIRY_DETAILS_SUCCESS = 'GET_ENQUIRY_DETAILS_SUCCESS';
export const SAVE_SUBSCRIPTION_DETAILS = 'SAVE_PAYMENT_DETAILS';
export const SAVE_SUBSCRIPTION_DETAILS_SUCCESS = 'SAVE_PAYMENT_DETAILS_SUCCESS';
export const SAVE_INSTALLMENT_DETAIL = 'SAVE_INSTALLMENT_DETAIL';
export const GET_PRODUCT_HIT_DETAIL = 'GET_PRODUCT_HIT_DETAIL';
export const GET_PRODUCT_HIT_DETAIL_SUCCESS = 'GET_PRODUCT_HIT_DETAIL_SUCCESS';
export const GET_PACKAGE_HIT_DETAIL = 'GET_PACKAGE_HIT_DETAIL';
export const GET_PACKAGE_HIT_DETAIL_SUCCESS = 'GET_PACKAGE_HIT_DETAIL_SUCCESS';
export const ON_DISCOUNT_CHANGE = 'ON_DISCOUNT_CHANGE';
export const ON_TOTALPROCE_CHANGE = 'ON_TOTALPROCE_CHANGE';
export const ON_CLASS_CHANGE = 'ON_CLASS_CHANGE';
export const CART_EMPTY = 'CART_EMPTY';
export const ON_CLOSE_CHANGESALE_TRANSFER = 'ON_CLOSE_CHANGESALE_TRANSFER';
export const ON_ASSIGNTRAINER_CHANGE = 'ON_ASSIGNTRAINER_CHANGE';
export const ON_COMPLEMENTCATEGORY_CHANGE = 'ON_COMPLEMENTCATEGORY_CHANGE';
//
// export const GET_UNFINISHEDCART_LIST = 'GET_UNFINISHEDCART_LIST';
// export const GET_UNFINISHEDCART_LIST_SUCCESS = 'GET_UNFINISHEDCART_LIST_SUCCESS';
// export const DELETE_UNFINISHEDCART = 'DELETE_UNFINISHEDCART';
// export const OPEN_UNFINISHEDCART_IN_EXPRESSSALE = 'OPEN_UNFINISHEDCART_IN_EXPRESSSALE';
//
//
// // member subscription
// export const GET_SUBSCRIPTION_LIST = 'GET_SUBSCRIPTION_LIST';
// export const GET_SUBSCRIPTION_LIST_SUCCESS = 'GET_SUBSCRIPTION_LIST_SUCCESS';
//
// export const SAVE_SUBSCRIPTION_FOLLOWUP = 'SAVE_SUBSCRIPTION_FOLLOWUP';
// export const SAVE_SUBSCRIPTION_FOLLOWUP_SUCCESS = 'SAVE_SUBSCRIPTION_FOLLOWUP_SUCCESS';
// export const ON_CHANGE_SUBSCRIPTION = 'ON_CHANGE_SUBSCRIPTION';
//
// export const OPEN_VIEW_MEMBER_FOLLOWUP_MODEL = 'OPEN_VIEW_MEMBER_FOLLOWUP_MODEL';
// export const CLOSE_VIEW_MEMBER_FOLLOWUP_MODEL = 'CLOSE_VIEW_MEMBER_FOLLOWUP_MODEL';
//
// //member personal training
//
// export const GET_MEMBER_PERSONALTRAINING_LIST = 'GET_MEMBER_PERSONALTRAINING_LIST';
// export const GET_MEMBER_PERSONALTRAINING_LIST_SUCCESS = 'GET_MEMBER_PERSONALTRAINING_LIST_SUCCESS';
// export const OPEN_ADD_ASSIGNTRAINER_MODEL = 'OPEN_ADD_ASSIGNTRAINER_MODEL';
// export const OPEN_ADD_ASSIGNTRAINER_MODEL_SUCCESS = 'OPEN_ADD_ASSIGNTRAINER_MODEL_SUCCESS';
// export const CLOSE_ADD_ASSIGNTRAINER_MODEL = 'CLOSE_ADD_ASSIGNTRAINER_MODEL';
// export const SAVE_ASSIGNTRAINER = 'SAVE_ASSIGNTRAINER';
// export const SAVE_ASSIGNTRAINER_SUCCESS = 'SAVE_ASSIGNTRAINER_SUCCESS';
// export const SAVE_NOTE_NEXTSESSION = 'SAVE_NOTE_NEXTSESSION';
// export const SAVE_NOTE_NEXTSESSION_SUCCESS = 'SAVE_NOTE_NEXTSESSION_SUCCESS';
// export const SAVE_PTSLOT = 'SAVE_PTSLOT';
// export const SAVE_PTSLOT_SUCCESS = 'SAVE_PTSLOT_SUCCESS';
// export const SAVE_PTSLOT_FAILURE = 'SAVE_PTSLOT_FAILURE';
// export const OPEN_VIEW_PT_SLOT_MODEL = 'OPEN_VIEW_PT_SLOT_MODEL';
// export const OPEN_VIEW_PT_SLOT_MODEL_SUCCESS = 'OPEN_VIEW_PT_SLOT_MODEL_SUCCESS';
// export const CLOSE_VIEW_PT_SLOT_MODEL = 'CLOSE_VIEW_PT_SLOT_MODEL';
// export const DELETE_PT_SLOT = 'DELETE_PT_SLOT';
// export const DELETE_PT_SLOT_SUCCESS = 'DELETE_PT_SLOT_SUCCESS';
// export const GET_MEMBER_PTSLOT_DETAIL= 'GET_MEMBER_PTSLOT_DETAIL';
// export const GET_MEMBER_PTSLOT_DETAIL_SUCCESS = 'GET_MEMBER_PTSLOT_DETAIL_SUCCESS';
// export const SAVE_ONLINEACCESSURL = 'SAVE_ONLINEACCESSURL';
// export const SAVE_ONLINEACCESSURL_SUCCESS = 'SAVE_ONLINEACCESSURL_SUCCESS';
//
// // employee management
//
export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const GET_EMPLOYEES_SUCCESS = 'GET_EMPLOYEES_SUCCESS';
export const OPEN_ADD_NEW_EMPLOYEE_MODEL = 'OPEN_ADD_NEW_EMPLOYEE_MODEL';
export const OPEN_ADD_NEW_EMPLOYEE_MODEL_SUCCESS = 'OPEN_ADD_NEW_EMPLOYEE_MODEL_SUCCESS';
export const CLOSE_ADD_NEW_EMPLOYEE_MODEL = 'CLOSE_ADD_NEW_EMPLOYEE_MODEL';
export const OPEN_EDIT_EMPLOYEE_MODEL = 'OPEN_EDIT_EMPLOYEE_MODEL';
export const OPEN_EDIT_EMPLOYEE_MODEL_SUCCESS = 'OPEN_EDIT_EMPLOYEE_MODEL_SUCCESS';
export const OPEN_VIEW_EMPLOYEE_MODEL = 'OPEN_VIEW_EMPLOYEE_MODEL';
export const OPEN_VIEW_EMPLOYEE_MODEL_SUCCESS = 'OPEN_VIEW_EMPLOYEE_MODEL_SUCCESS';
export const CLOSE_VIEW_EMPLOYEE_MODEL = 'CLOSE_VIEW_EMPLOYEE_MODEL';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE';
export const SAVE_EMPLOYEES_SUCCESS = 'SAVE_EMPLOYEES_SUCCESS';
export const SET_EMPLOYEE_DEFAULT_BRANCH = 'SET_EMPLOYEE_DEFAULT_BRANCH';
export const SET_EMPLOYEE_DEFAULT_BRANCH_SUCCESS = 'SET_EMPLOYEE_DEFAULT_BRANCH_SUCCESS';
export const OPEN_STARTER_VIEW_EMPLOYEE_MODEL = 'OPEN_STARTER_VIEW_EMPLOYEE_MODEL';
export const OPEN_STARTER_VIEW_EMPLOYEE_MODEL_SUCCESS = 'OPEN_STARTER_VIEW_EMPLOYEE_MODEL_SUCCESS';
export const CLOSE_STARTER_VIEW_EMPLOYEE_MODEL = 'CLOSE_STARTER_VIEW_EMPLOYEE_MODEL';
//
// //Client Signup
export const CLIENT_SIGNUP_REQUEST = 'CLIENT_SIGNUP_REQUEST';
export const CLIENT_SIGNUP_REQUEST_SUCCESS = 'CLIENT_SIGNUP_REQUEST_SUCCESS';
export const ON_CLIENT_SIGNUP_VERIFICATION = 'ON_CLIENT_SIGNUP_VERIFICATION';
export const SAVE_CLIENT_ESTABLISHMENT_INFO = 'SAVE_CLIENT_ESTABLISHMENT_INFO';
export const SAVE_CLIENT_ORGANIZATION_INFO = 'SAVE_CLIENT_ORGANIZATION_INFO';
export const SAVE_CLIENT_URL = 'SAVE_CLIENT_URL';
export const SAVE_CLIENT_URL_SUCCESS = 'SAVE_CLIENT_URL_SUCCESS';
export const CLIENT_SIGNUP_HANDLE_BACK_BUTTON = 'CLIENT_SIGNUP_HANDLE_BACK_BUTTON';


export const CLIENT_SIGNIN_REQUEST = 'CLIENT_SIGNIN_REQUEST';
export const CLIENT_SIGNIN_REQUEST_SUCCESS = 'CLIENT_SIGNIN_REQUEST_SUCCESS';
//
// // member management
// export const GET_MEMBERS = 'GET_MEMBERS';
// export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
// export const GET_MEMBERS_FAILURE = 'GET_MEMBERS_FAILURE';
// export const OPEN_ADD_NEW_MEMBER_MODEL = 'OPEN_ADD_NEW_MEMBER_MODEL';
// export const OPEN_ADD_NEW_MEMBER_MODEL_SUCCESS = 'OPEN_ADD_NEW_MEMBER_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_MEMBER_MODEL = 'CLOSE_ADD_NEW_MEMBER_MODEL';
// export const SAVE_MEMBER = 'SAVE_MEMBER';
// export const SAVE_MEMBER_SUCCESS = 'SAVE_MEMBER_SUCCESS';
//
// export const OPEN_VIEW_MEMBER_MODEL = 'OPEN_VIEW_MEMBER_MODEL';
// export const OPEN_VIEW_MEMBER_MODEL_SUCCESS = 'OPEN_VIEW_MEMBER_MODEL_SUCCESS';
// export const CLOSE_VIEW_MEMBER_MODEL = 'CLOSE_VIEW_MEMBER_MODEL';
// export const OPEN_EDIT_MEMBER_MODEL = 'OPEN_EDIT_MEMBER_MODEL';
// export const OPEN_EDIT_MEMBER_MODEL_SUCCESS = 'OPEN_EDIT_MEMBER_MODEL_SUCCESS';
//
// export const DELETE_MEMBER = 'DELETE_MEMBER';
//
// export const IMPORT_MEMBER = 'IMPORT_MEMBER';
// export const IMPORT_MEMBER_SUCCESS = 'IMPORT_MEMBER_SUCCESS';
// export const IMPORT_MEMBER_LIST = 'IMPORT_MEMBER_LIST';
// export const IMPORT_MEMBER_LIST_SUCCESS = 'IMPORT_MEMBER_LIST_SUCCESS';
//
// export const GET_MEMBERPROFILE_MEMBERSHIP = 'GET_MEMBERPROFILE_MEMBERSHIP';
// export const GET_MEMBERPROFILE_MEMBERSHIP_SUCCESS = 'GET_MEMBERPROFILE_MEMBERSHIP_SUCCESS';
//
// export const SAVE_ACTIVEMEMBERSHIP_CHANGEDATE = 'SAVE_ACTIVEMEMBERSHIP_CHANGEDATE';
// export const SAVE_ACTIVEMEMBERSHIP_CHANGEDATE_SUCCESS = 'SAVE_ACTIVEMEMBERSHIP_CHANGEDATE_SUCCESS';
//
// export const OPEN_MEMBERSHIP_CHANGEDATE_MODEL = 'OPEN_MEMBERSHIP_CHANGEDATE_MODEL';
// export const OPEN_MEMBERSHIP_CHANGEDATE_MODEL_SUCCESS = 'OPEN_MEMBERSHIP_CHANGEDATE_MODEL_SUCCESS';
// export const CLOSE_MEMBERSHIP_CHANGEDATE_MODEL = 'CLOSE_MEMBERSHIP_CHANGEDATE_MODEL';
//
// export const OPEN_CANCEL_PAYMENT_MODEL = 'OPEN_CANCEL_PAYMENT_MODEL';
// export const CLOSE_CANCEL_PAYMENT_MODEL = 'CLOSE_CANCEL_PAYMENT_MODEL';
// export const SAVE_CANCEL_PAYMENT = 'SAVE_CANCEL_PAYMENT';
// export const SAVE_CANCEL_PAYMENT_SUCCESS = 'SAVE_CANCEL_PAYMENT_SUCCESS';
//
// export const OPEN_EDIT_MEMBER_CHANGESTATUS_MODEL = 'OPEN_EDIT_MEMBER_CHANGESTATUS_MODEL';
// export const CLOSE_EDIT_MEMBER_CHANGESTATUS_MODEL = 'CLOSE_EDIT_MEMBER_CHANGESTATUS_MODEL';
// export const SAVE_MEMBER_STATUS = 'SAVE_MEMBER_STATUS';
// export const SAVE_MEMBER_STATUS_SUCCESS = 'SAVE_MEMBER_STATUS_SUCCESS';
//
// export const OPEN_MEMBER_BALANCE_ADJUSTMENT_MODEL = 'OPEN_MEMBER_BALANCE_ADJUSTMENT_MODEL';
// export const CLOSE_MEMBER_BALANCE_ADJUSTMENT_MODEL = 'CLOSE_MEMBER_BALANCE_ADJUSTMENT_MODEL';
// export const SAVE_MEMBER_BALANCE_ADJUSTMENT = 'SAVE_MEMBER_BALANCE_ADJUSTMENT';
// export const SAVE_MEMBER_BALANCE_ADJUSTMENT_SUCCESS = 'SAVE_MEMBER_BALANCE_ADJUSTMENT_SUCCESS';
//
// export const MEMBER_HANDLE_CHANGE_SELECT_ALL = 'MEMBER_HANDLE_CHANGE_SELECT_ALL';
// export const MEMBER_HANDLE_SINGLE_CHECKBOX_CHANGE = 'MEMBER_HANDLE_SINGLE_CHECKBOX_CHANGE';
// export const OPEN_CHANGE_MEMBER_SALESBY_MODEL = 'OPEN_CHANGE_MEMBER_SALESBY_MODEL';
// export const CLOSE_CHANGE_MEMBER_SALESBY_MODEL = 'CLOSE_CHANGE_MEMBER_SALESBY_MODEL';
// export const SAVE_CHANGE_MEMBER_SALESBY = 'SAVE_CHANGE_MEMBER_SALESBY';
// export const SAVE_CHANGE_MEMBER_SALESBY_SUCCESS = 'SAVE_CHANGE_MEMBER_SALESBY_SUCCESS';
//
//
// //Member Disclaimer List
//
// export const GET_MEMBER_DISCLAIMER_LIST = 'GET_MEMBER_DISCLAIMER_LIST';
// export const GET_MEMBER_DISCLAIMER_LIST_SUCCESS = 'GET_MEMBER_DISCLAIMER_LIST_SUCCESS';
// export const OPEN_ADD_MEMBER_CONSULTATIONNOTE_MODEL = 'OPEN_ADD_MEMBER_CONSULTATIONNOTE_MODEL';
// export const CLOSE_ADD_MEMBER_CONSULTATIONNOTE_MODEL = 'CLOSE_ADD_MEMBER_CONSULTATIONNOTE_MODEL';
// export const SAVE_MEMBER_CONSULTATIONNOTE = 'SAVE_MEMBER_CONSULTATIONNOTE';
// export const SAVE_MEMBER_CONSULTATIONNOTE_SUCCESS = 'SAVE_MEMBER_CONSULTATIONNOTE_SUCCESS';
// export const RESET_MEMBER_DISCLAIMER = 'RESET_MEMBER_DISCLAIMER';
//
//
// //SERVICE
// export const GET_SERVICES = 'GET_SERVICES';
// export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
// export const OPEN_ADD_NEW_SERVICE_MODEL = 'OPEN_ADD_NEW_SERVICE_MODEL';
// export const OPEN_ADD_NEW_SERVICE_MODEL_SUCCESS = 'OPEN_ADD_NEW_SERVICE_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_SERVICE_MODEL = 'CLOSE_ADD_NEW_SERVICE_MODEL';
// export const SAVE_SERVICE = 'SAVE_SERVICE';
// export const SAVE_SERVICE_SUCCESS = 'SAVE_SERVICE_SUCCESS';
// export const OPEN_VIEW_SERVICE_MODEL = 'OPEN_VIEW_SERVICE_MODEL';
// export const OPEN_VIEW_SERVICE_MODEL_SUCCESS = 'OPEN_VIEW_SERVICE_MODEL_SUCCESS';
// export const CLOSE_VIEW_SERVICE_MODEL = 'CLOSE_VIEW_SERVICE_MODEL';
// export const DELETE_SERVICE = 'DELETE_SERVICE';
// export const OPEN_EDIT_SERVICE_MODEL = 'OPEN_EDIT_SERVICE_MODEL';
// export const OPEN_EDIT_SERVICE_MODEL_SUCCESS = 'OPEN_EDIT_SERVICE_MODEL_SUCCESS';
// export const GET_SERVICES_PARALLELLIST = 'GET_SERVICES_PARALLELLIST';
// export const GET_SERVICES_PARALLELLIST_SUCCESS = 'GET_SERVICES_PARALLELLIST_SUCCESS';
//
//
// export const SERVICE_HANDLE_CHANGE_SELECT_ALL = 'SERVICE_HANDLE_CHANGE_SELECT_ALL';
// export const SERVICE_HANDLE_SINGLE_CHECKBOX_CHANGE = 'SERVICE_HANDLE_SINGLE_CHECKBOX_CHANGE';
// export const OPEN_ENABLEONLINESALE_SERVICE_MODEL = 'OPEN_ENABLEONLINESALE_SERVICE_MODEL';
// export const CLOSE_ENABLEONLINESALE_SERVICE_MODEL = 'CLOSE_ENABLEONLINESALE_SERVICE_MODEL';
// export const OPEN_DISABLEONLINESALE_SERVICE_MODEL = 'OPEN_DISABLEONLINESALE_SERVICE_MODEL';
// export const CLOSE_DISABLEONLINESALE_SERVICE_MODEL = 'CLOSE_DISABLEONLINESALE_SERVICE_MODEL';
// export const SAVE_ENABLEONLINESALE_SERVICE = 'SAVE_ENABLEONLINESALE_SERVICE';
// export const SAVE_ENABLEONLINESALE_SERVICE_SUCCESS = 'SAVE_ENABLEONLINESALE_SERVICE_SUCCESS';
//
//
// export const PRODUCT_HANDLE_CHANGE_SELECT_ALL = 'PRODUCT_HANDLE_CHANGE_SELECT_ALL';
// export const PRODUCT_HANDLE_SINGLE_CHECKBOX_CHANGE = 'PRODUCT_HANDLE_SINGLE_CHECKBOX_CHANGE';
// export const OPEN_ENABLEONLINESALE_PRODUCT_MODEL = 'OPEN_ENABLEONLINESALE_PRODUCT_MODEL';
// export const CLOSE_ENABLEONLINESALE_PRODUCT_MODEL = 'CLOSE_ENABLEONLINESALE_PRODUCT_MODEL';
// export const OPEN_DISABLEONLINESALE_PRODUCT_MODEL = 'OPEN_DISABLEONLINESALE_PRODUCT_MODEL';
// export const CLOSE_DISABLEONLINESALE_PRODUCT_MODEL = 'CLOSE_DISABLEONLINESALE_PRODUCT_MODEL';
// export const SAVE_ENABLEONLINESALE_PRODUCT = 'SAVE_ENABLEONLINESALE_PRODUCT';
// export const SAVE_ENABLEONLINESALE_PRODUCT_SUCCESS = 'SAVE_ENABLEONLINESALE_PRODUCT_SUCCESS';
//
// //COMPETITION
// export const GET_COMPETITION = 'GET_COMPETITION';
// export const GET_COMPETITION_SUCCESS = 'GET_COMPETITION_SUCCESS';
// export const OPEN_ADD_NEW_COMPETITION_MODEL = 'OPEN_ADD_NEW_COMPETITION_MODEL';
// export const OPEN_ADD_NEW_COMPETITION_MODEL_SUCCESS = 'OPEN_ADD_NEW_COMPETITION_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_COMPETITION_MODEL = 'CLOSE_ADD_NEW_COMPETITION_MODEL';
// export const SAVE_COMPETITION = 'SAVE_COMPETITION';
// export const SAVE_COMPETITION_SUCCESS = 'SAVE_COMPETITION_SUCCESS';
// export const OPEN_VIEW_COMPETITION_MODEL = 'OPEN_VIEW_COMPETITION_MODEL';
// export const OPEN_VIEW_COMPETITION_MODEL_SUCCESS = 'OPEN_VIEW_COMPETITION_MODEL_SUCCESS';
// export const CLOSE_VIEW_COMPETITION_MODEL = 'CLOSE_VIEW_COMPETITION_MODEL';
// export const DELETE_COMPETITION = 'DELETE_COMPETITION';
// export const OPEN_EDIT_COMPETITION_MODEL = 'OPEN_EDIT_COMPETITION_MODEL';
// export const OPEN_EDIT_COMPETITION_MODEL_SUCCESS = 'OPEN_EDIT_COMPETITION_MODEL_SUCCESS';
//
// export const GET_PARTICIPANT = 'GET_PARTICIPANT';
// export const GET_PARTICIPANT_SUCCESS = 'GET_PARTICIPANT_SUCCESS';
// export const OPEN_ADD_NEW_PARTICIPANT_MODEL = 'OPEN_ADD_NEW_PARTICIPANT_MODEL';
// export const CLOSE_ADD_NEW_PARTICIPANT_MODEL = 'CLOSE_ADD_NEW_PARTICIPANT_MODEL';
// export const SAVE_PARTICIPANT = 'SAVE_PARTICIPANT';
// export const SAVE_PARTICIPANT_SUCCESS = 'SAVE_PARTICIPANT_SUCCESS';
// export const OPEN_EDIT_PARTICIPANT_MODEL = 'OPEN_EDIT_PARTICIPANT_MODEL';
// export const OPEN_EDIT_PARTICIPANT_MODEL_SUCCESS = 'OPEN_EDIT_PARTICIPANT_MODEL_SUCCESS';
// export const DELETE_PARTICIPANT = 'DELETE_PARTICIPANT';
// export const OPEN_ADD_NEW_PARTICIPANT_MEASUREMENT_MODEL = 'OPEN_ADD_NEW_PARTICIPANT_MEASUREMENT_MODEL';
// export const OPEN_ADD_NEW_PARTICIPANT_MEASUREMENT_MODEL_SUCCESS = 'OPEN_ADD_NEW_PARTICIPANT_MEASUREMENT_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_PARTICIPANT_MEASUREMENT_MODEL = 'CLOSE_ADD_NEW_PARTICIPANT_MEASUREMENT_MODEL';
// export const SAVE_PARTICIPANT_MEASUREMENT = 'SAVE_PARTICIPANT_MEASUREMENT';
// export const SAVE_PARTICIPANT_MEASUREMENT_SUCCESS = 'SAVE_PARTICIPANT_MEASUREMENT_SUCCESS';
//
// //ENQUIRY
// export const OPEN_ADD_NEW_ENQUIRY_MODEL = 'OPEN_ADD_NEW_ENQUIRY_MODEL';
// export const OPEN_ADD_NEW_ENQUIRY_MODEL_SUCCESS = 'OPEN_ADD_NEW_ENQUIRY_MODEL_SUCCESS';
// export const GET_ENQUIRY = 'GET_ENQUIRY';
// export const GET_ENQUIRY_SUCCESS = 'GET_ENQUIRY_SUCCESS';
// export const CLOSE_ADD_NEW_ENQUIRY_MODEL = 'CLOSE_ADD_NEW_ENQUIRY_MODEL';
// export const SAVE_ENQUIRY = 'SAVE_ENQUIRY';
// export const SAVE_ENQUIRY_SUCCESS = 'SAVE_ENQUIRY_SUCCESS';
// export const OPEN_VIEW_ENQUIRY_MODEL = 'OPEN_VIEW_ENQUIRY_MODEL';
// export const OPEN_VIEW_ENQUIRY_MODEL_SUCCESS = 'OPEN_VIEW_ENQUIRY_MODEL_SUCCESS';
// export const CLOSE_VIEW_ENQUIRY_MODEL = 'CLOSE_VIEW_ENQUIRY_MODEL';
// export const DELETE_ENQUIRY = 'DELETE_ENQUIRY';
// export const OPEN_EDIT_ENQUIRY_MODEL = 'OPEN_EDIT_ENQUIRY_MODEL';
// export const OPEN_EDIT_ENQUIRY_MODEL_SUCCESS = 'OPEN_EDIT_ENQUIRY_MODEL_SUCCESS';
// export const SERVICE_LIST_IN_ENQUIRY = 'SERVICE_LIST_IN_ENQUIRY';
// export const SERVICE_LIST_IN_ENQUIRY_SUCCESS = 'SERVICE_LIST_IN_ENQUIRY_SUCCESS';
// export const OPEN_VIEW_ENQUIRY_STATUS_MODEL = 'OPEN_VIEW_ENQUIRY_STATUS_MODEL';
// export const OPEN_VIEW_ENQUIRY_STATUS_MODEL_SUCCESS = 'OPEN_VIEW_ENQUIRY_STATUS_MODEL_SUCCESS';
// export const CLOSE_VIEW_ENQUIRY_STATUS_MODEL = 'CLOSE_VIEW_ENQUIRY_STATUS_MODEL';
// export const SAVE_ENQUIRY_STATUS = 'SAVE_ENQUIRY_STATUS';
// export const SAVE_ENQUIRY_STATUS_SUCCESS = 'SAVE_ENQUIRY_STATUS_SUCCESS';
// export const IMPORT_ENQUIRY = 'IMPORT_ENQUIRY';
// export const IMPORT_ENQUIRY_SUCCESS = 'IMPORT_ENQUIRY_SUCCESS';
// export const IMPORT_ENQUIRY_LIST = 'IMPORT_ENQUIRY_LIST';
// export const IMPORT_ENQUIRY_LIST_SUCCESS = 'IMPORT_ENQUIRY_LIST_SUCCESS';
// export const HANDLE_CHANGE_SELECT_ALL = 'HANDLE_CHANGE_SELECT_ALL';
// export const HANDLE_SINGLE_CHECKBOX_CHANGE = 'HANDLE_SINGLE_CHECKBOX_CHANGE';
// export const OPEN_TRANSFER_ENQUIRY_MODEL = 'OPEN_TRANSFER_ENQUIRY_MODEL';
// export const CLOSE_TRANSFER_ENQUIRY_MODEL = 'CLOSE_TRANSFER_ENQUIRY_MODEL';
// export const SAVE_TRANSFER_ENQUIRY = 'SAVE_TRANSFER_ENQUIRY';
// export const SAVE_TRANSFER_ENQUIRY_SUCCESS = 'SAVE_TRANSFER_ENQUIRY_SUCCESS';
//
// //visitorbook
// export const OPEN_ADD_NEW_VISITOR_MODEL = 'OPEN_ADD_NEW_VISITOR_MODEL';
// export const OPEN_ADD_NEW_VISITOR_MODEL_SUCCESS = 'OPEN_ADD_NEW_VISITOR_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_VISITOR_MODEL = 'CLOSE_ADD_NEW_VISITOR_MODEL';
// export const SAVE_VISITOR = 'SAVE_VISITOR';
// export const SAVE_VISITOR_SUCCESS = 'SAVE_VISITOR_SUCCESS';
// export const GET_VISITORS = 'GET_VISITORS';
// export const GET_VISITORS_SUCCESS = 'GET_VISITORS_SUCCESS';
// export const SAVE_VISITOR_OUTTIME = 'SAVE_VISITOR_OUTTIME';
// export const OPEN_VIEW_VISITOR_MODEL = 'OPEN_VIEW_VISITOR_MODEL';
// export const OPEN_VIEW_VISITOR_MODEL_SUCCESS = 'OPEN_VIEW_VISITOR_MODEL_SUCCESS';
// export const CLOSE_VIEW_VISITOR_MODEL = 'CLOSE_VIEW_VISITOR_MODEL';
// export const BOOK_GYM_ACCESSSLOT_MEMBER_VISITOR = 'BOOK_GYM_ACCESSSLOT_MEMBER_VISITOR';
// export const BOOK_GYM_ACCESSSLOT_MEMBER_VISITOR_SUCCESS = 'BOOK_GYM_ACCESSSLOT_MEMBER_VISITOR_SUCCESS';
// export const GET_MEMBER_GYM_ACCESSSLOT = 'GET_MEMBER_GYM_ACCESSSLOT';
// export const GET_MEMBER_GYM_ACCESSSLOT_SUCCESS = 'GET_MEMBER_GYM_ACCESSSLOT_SUCCESS';
// export const OPEN_EDIT_VISITOR_MODEL = 'OPEN_EDIT_VISITOR_MODEL';
// export const OPEN_EDIT_VISITOR_MODEL_SUCCESS = 'OPEN_EDIT_VISITOR_MODEL_SUCCESS';
//
// //class
// export const OPEN_ADD_NEW_CLASS_MODEL = 'OPEN_ADD_NEW_CLASS_MODEL';
// export const OPEN_ADD_NEW_CLASS_MODEL_SUCCESS = 'OPEN_ADD_NEW_CLASS_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_CLASS_MODEL = 'CLOSE_ADD_NEW_CLASS_MODEL';
// export const GET_CLASSES = 'GET_CLASSES';
// export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
// export const SAVE_CLASS = 'SAVE_CLASS';
// export const SAVE_CLASS_SUCCESS = 'SAVE_CLASS_SUCCESS';
// export const OPEN_EDIT_CLASS_MODEL = 'OPEN_EDIT_CLASS_MODEL';
// export const OPEN_EDIT_CLASS_MODEL_SUCCESS = 'OPEN_EDIT_CLASS_MODEL_SUCCESS';
// export const OPEN_VIEW_CLASS_MODEL = 'OPEN_VIEW_CLASS_MODEL';
// export const OPEN_VIEW_CLASS_MODEL_SUCCESS = 'OPEN_VIEW_CLASS_MODEL_SUCCESS';
// export const CLOSE_VIEW_CLASS_MODEL = 'CLOSE_VIEW_CLASS_MODEL';
// export const DELETE_CLASS = 'DELETE_CLASS';
//
// export const OPEN_ADD_ASSIGNMEMBER_MODEL = 'OPEN_ADD_ASSIGNMEMBER_MODEL';
// export const OPEN_ADD_ASSIGNMEMBER_MODEL_SUCCESS = 'OPEN_ADD_ASSIGNMEMBER_MODEL_SUCCESS';
// export const CLOSE_ADD_ASSIGNMEMBER_MODEL = 'CLOSE_ADD_ASSIGNMEMBER_MODEL';
// export const SAVE_ASSIGNMEMBER = 'SAVE_ASSIGNMEMBER';
// export const SAVE_ASSIGNMEMBER_SUCCESS = 'SAVE_ASSIGNMEMBER_SUCCESS';
// export const DELETE_ASSIGNMEMBER = 'DELETE_ASSIGNMEMBER';
// export const GET_ASSIGNMEMBERS = 'GET_ASSIGNMEMBERS';
// export const GET_ASSIGNMEMBERS_SUCCESS = 'GET_ASSIGNMEMBERS_SUCCESS';
// export const GET_CLASS_BOOKED_AND_INTERESTED_LIST = 'GET_CLASS_BOOKED_AND_INTERESTED_LIST';
// export const GET_CLASS_BOOKED_AND_INTERESTED_LIST_SUCCESS = 'GET_CLASS_BOOKED_AND_INTERESTED_LIST_SUCCESS';
// export const STAFF_SAVE_MEMBER_CLASS_BOOKING = 'STAFF_SAVE_MEMBER_CLASS_BOOKING';
// export const STAFF_SAVE_MEMBER_CLASS_BOOKING_SUCCESS = 'STAFF_SAVE_MEMBER_CLASS_BOOKING_SUCCESS';
// export const DELETE_CLASS_BOOKED = 'DELETE_CLASS_BOOKED';
//
// export const SAVE_CLASS_ONLINEACCESSURL = 'SAVE_CLASS_ONLINEACCESSURL';
// export const SAVE_CLASS_ONLINEACCESSURL_SUCCESS = 'SAVE_CLASS_ONLINEACCESSURL_SUCCESS';
// export const OPEN_ADD_CLASS_ONLINEACCESSURL_MODEL = 'OPEN_ADD_CLASS_ONLINEACCESSURL_MODEL';
// export const CLOSE_ADD_CLASS_ONLINEACCESSURL_MODEL = 'CLOSE_ADD_CLASS_ONLINEACCESSURL_MODEL';
// export const CLASS_CANCEL = 'CLASS_CANCEL';
// export const CLASS_CANCEL_SUCCESS = 'CLASS_CANCEL_SUCCESS';
//
//
// //changeSale
// export const GET_CHANGESUBSCRIPTIONSALES = 'GET_CHANGESUBSCRIPTIONSALES';
// export const GET_CHANGESUBSCRIPTIONSALES_SUCCESS = 'GET_CHANGESUBSCRIPTIONSALES_SUCCESS';
// export const CHANGE_SALE = 'CHANGE_SALE';
// export const CHANGE_SALE_SUCCESS = 'CHANGE_SALE_SUCCESS';
// export const OPEN_CHANGESALE_MODEL = 'OPEN_CHANGESALE_MODEL';
// export const OPEN_CHANGESALE_MODEL_SUCCESS = 'OPEN_CHANGESALE_MODEL_SUCCESS';
// export const CLOSE_CHANGESALE_MODEL = 'CLOSE_CHANGESALE_MODEL';
// export const ON_CHANGE = 'ON_CHANGE';
//
//
// //class Performance
// export const GET_CLASS_PERFORMANCE = 'GET_CLASS_PERFORMANCE';
// export const GET_CLASS_PERFORMANCE_SUCCESS = 'GET_CLASS_PERFORMANCE_SUCCESS';
// export const OPEN_VIEW_CLASS_PERFORMANCE_MODEL = 'OPEN_VIEW_CLASS_PERFORMANCE_MODEL';
// export const OPEN_VIEW_CLASS_PERFORMANCE_MODEL_SUCCESS = 'OPEN_VIEW_CLASS_PERFORMANCE_MODEL_SUCCESS';
// export const CLOSE_VIEW_CLASS_PERFORMANCE_MODEL = 'CLOSE_VIEW_CLASS_PERFORMANCE_MODEL';
// export const CONFIRMED_CLASS_COMMSSION = 'CONFIRMED_CLASS_COMMSSION';
//
// //zone
// export const OPEN_ADD_NEW_ZONE_MODEL = 'OPEN_ADD_NEW_ZONE_MODEL';
// export const OPEN_ADD_NEW_ZONE_MODEL_SUCCESS = 'OPEN_ADD_NEW_ZONE_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_ZONE_MODEL = 'CLOSE_ADD_NEW_ZONE_MODEL';
// export const GET_ZONES = 'GET_ZONES';
// export const GET_ZONES_SUCCESS = 'GET_ZONES_SUCCESS';
// export const SAVE_ZONE = 'SAVE_ZONE';
// export const SAVE_ZONE_SUCCESS = 'SAVE_ZONE_SUCCESS';
// export const OPEN_VIEW_ZONE_MODEL = 'OPEN_VIEW_ZONE_MODEL';
// export const OPEN_VIEW_ZONE_MODEL_SUCCESS = 'OPEN_VIEW_ZONE_MODEL_SUCCESS';
// export const CLOSE_VIEW_ZONE_MODEL = 'CLOSE_VIEW_ZONE_MODEL';
// export const OPEN_EDIT_ZONE_MODEL = 'OPEN_EDIT_ZONE_MODEL';
// export const OPEN_EDIT_ZONE_MODEL_SUCCESS = 'OPEN_EDIT_ZONE_MODEL_SUCCESS';
// export const DELETE_ZONE = 'DELETE_ZONE';
//
// //branch
// export const OPEN_ADD_NEW_BRANCH_MODEL = 'OPEN_ADD_NEW_BRANCH_MODEL';
// export const OPEN_ADD_NEW_BRANCH_MODEL_SUCCESS = 'OPEN_ADD_NEW_BRANCH_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_BRANCH_MODEL = 'CLOSE_ADD_NEW_BRANCH_MODEL';
// export const GET_BRANCHES = 'GET_BRANCHES';
// export const GET_BRANCHES_SUCCESS = 'GET_BRANCHES_SUCCESS';
// export const SAVE_BRANCH = 'SAVE_BRANCH';
// export const SAVE_BRANCH_SUCCESS = 'SAVE_BRANCH_SUCCESS';
// export const OPEN_VIEW_BRANCH_MODEL = 'OPEN_VIEW_BRANCH_MODEL';
// export const OPEN_VIEW_BRANCH_MODEL_SUCCESS = 'OPEN_VIEW_BRANCH_MODEL_SUCCESS';
// export const CLOSE_VIEW_BRANCH_MODEL = 'CLOSE_VIEW_BRANCH_MODEL';
// export const DELETE_BRANCH = 'DELETE_BRANCH';
// export const OPEN_EDIT_BRANCH_MODEL = 'OPEN_EDIT_BRANCH_MODEL';
// export const OPEN_EDIT_BRANCH_MODEL_SUCCESS = 'OPEN_EDIT_BRANCH_MODEL_SUCCESS';
//
// //measurement
// export const OPEN_ADD_NEW_MEASUREMENT_MODEL = 'OPEN_ADD_NEW_MEASUREMENT_MODEL';
// export const OPEN_ADD_NEW_MEASUREMENT_MODEL_SUCCESS = 'OPEN_ADD_NEW_MEASUREMENT_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_MEASUREMENT_MODEL = 'CLOSE_ADD_NEW_MEASUREMENT_MODEL';
// export const GET_MEASUREMENTS = 'GET_MEASUREMENTS';
// export const GET_MEASUREMENTS_SUCCESS = 'GET_MEASUREMENTS_SUCCESS';
// export const SAVE_MEASUREMENT = 'SAVE_MEASUREMENT';
// export const SAVE_MEASUREMENT_SUCCESS = 'SAVE_MEASUREMENT_SUCCESS';
// export const OPEN_VIEW_MEASUREMENT_MODEL = 'OPEN_VIEW_MEASUREMENT_MODEL';
// export const OPEN_VIEW_MEASUREMENT_MODEL_SUCCESS = 'OPEN_VIEW_MEASUREMENT_MODEL_SUCCESS';
// export const CLOSE_VIEW_MEASUREMENT_MODEL = 'CLOSE_VIEW_MEASUREMENT_MODEL';
// export const OPEN_EDIT_MEASUREMENT_MODEL = 'OPEN_EDIT_MEASUREMENT_MODEL';
// export const OPEN_EDIT_MEASUREMENTMODEL_SUCCESS = 'OPEN_EDIT_MEASUREMENTMODEL_SUCCESS';
// export const GET_BODY_MEASUREMENT_DETAILS = 'GET_BODY_MEASUREMENT_DETAILS';
// export const GET_BODY_MEASUREMENT_DETAILS_SUCCESS = 'GET_BODY_MEASUREMENT_DETAILS_SUCCESS';
// export const OPEN_ADD_NEW_NOT_TAKEN_MEASUREMENT_MEMBER_MODEL = 'OPEN_ADD_NEW_NOT_TAKEN_MEASUREMENT_MEMBER_MODEL';
// export const CLOSE_ADD_NEW_NOT_TAKEN_MEASUREMENT_MEMBER_MODEL = 'CLOSE_ADD_NEW_NOT_TAKEN_MEASUREMENT_MEMBER_MODEL';
// export const OPEN_VIEW_MEASUREMENT_INBODY_MODEL = 'OPEN_VIEW_MEASUREMENT_INBODY_MODEL';
// export const OPEN_VIEW_MEASUREMENT_INBODY_MODEL_SUCCESS = 'OPEN_VIEW_MEASUREMENT_INBODY_MODEL_SUCCESS';
// export const CLOSE_VIEW_MEASUREMENT_INBODY_MODEL = 'CLOSE_VIEW_MEASUREMENT_INBODY_MODEL';
// export const OPEN_VIEW_INBODY_MEASUREMENT_MODEL = 'OPEN_VIEW_INBODY_MEASUREMENT_MODEL';
// export const OPEN_VIEW_INBODY_MEASUREMENT_MODEL_SUCCESS = 'OPEN_VIEW_INBODY_MEASUREMENT_MODEL_SUCCESS';
// export const CLOSE_VIEW_INBODY_MEASUREMENT_MODEL = 'CLOSE_VIEW_INBODY_MEASUREMENT_MODEL';
// export const OPEN_VIEW_MEASUREMENT_PDF_MODEL = 'OPEN_VIEW_MEASUREMENT_PDF_MODEL';
// export const CLOSE_VIEW_MEASUREMENT_PDF_MODEL = 'CLOSE_VIEW_MEASUREMENT_PDF_MODEL';
//
// //Dues
// export const GET_DUES = 'GET_DUES';
// export const GET_DUES_SUCCESS = 'GET_DUES_SUCCESS';
// export const SAVE_PAYMENT = 'SAVE_PAYMENT';
// export const SAVE_PAYMENT_SUCCESS = 'SAVE_PAYMENT_SUCCESS';
// export const OPEN_ADD_NEW_PAYMENT_MODEL = 'OPEN_ADD_NEW_PAYMENT_MODEL';
// export const OPEN_ADD_NEW_PAYMENT_MODEL_SUCCESS = 'OPEN_ADD_NEW_PAYMENT_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_PAYMENT_MODEL = 'CLOSE_ADD_NEW_PAYMENT_MODEL';
// export const GET_PENDING_CHEQUE_LIST = 'GET_PENDING_CHEQUE_LIST';
// export const GET_PENDING_CHEQUE_LIST_SUCCESS = 'GET_PENDING_CHEQUE_LIST_SUCCESS';
// export const CHANGE_CHEQUE_PAYMENT_STATUS = 'CHANGE_CHEQUE_PAYMENT_STATUS';
// export const CHANGE_CHEQUE_PAYMENT_STATUS_SUCCESS = 'CHANGE_CHEQUE_PAYMENT_STATUS_SUCCESS';
//
// //member feedback
//
// export const GET_TRAINERS_FEEDBACK_BYMEMBER = 'GET_TRAINERS_FEEDBACK_BYMEMBER';
// export const GET_TRAINERS_FEEDBACK_BYMEMBER_SUCCESS = 'GET_TRAINERS_FEEDBACK_BYMEMBER_SUCCESS';
// export const OPEN_VIEW_TRAINERS_FEEDBACK_BYMEMBER_MODEL = 'OPEN_VIEW_TRAINERS_FEEDBACK_BYMEMBER_MODEL';
// export const OPEN_VIEW_TRAINERS_FEEDBACK_BYMEMBER_MODEL_SUCCESS = 'OPEN_VIEW_TRAINERS_FEEDBACK_BYMEMBER_MODEL_SUCCESS';
// export const CLOSE_VIEW_TRAINERS_FEEDBACK_BYMEMBER_MODEL = 'CLOSE_VIEW_TRAINERS_FEEDBACK_BYMEMBER_MODEL';
//
// export const GET_TRAINERS_GS_FEEDBACK_BYMEMBER = 'GET_TRAINERS_GS_FEEDBACK_BYMEMBER';
// export const GET_TRAINERS_GS_FEEDBACK_BYMEMBER_SUCCESS = 'GET_TRAINERS_GS_FEEDBACK_BYMEMBER_SUCCESS';
// export const OPEN_VIEW_TRAINERS_GS_FEEDBACK_BYMEMBER_MODEL = 'OPEN_VIEW_TRAINERS_GS_FEEDBACK_BYMEMBER_MODEL';
// export const OPEN_VIEW_TRAINERS_GS_FEEDBACK_BYMEMBER_MODEL_SUCCESS = 'OPEN_VIEW_TRAINERS_GS_FEEDBACK_BYMEMBER_MODEL_SUCCESS';
// export const CLOSE_VIEW_TRAINERS_GS_FEEDBACK_BYMEMBER_MODEL = 'CLOSE_VIEW_TRAINERS_GS_FEEDBACK_BYMEMBER_MODEL';
//
// export const GET_TRAINERS_GENERALRATING_BYMEMBER = 'GET_TRAINERS_GENERALRATING_BYMEMBER';
// export const GET_TRAINERS_GENERALRATING_BYMEMBER_SUCCESS = 'GET_TRAINERS_GENERALRATING_BYMEMBER_SUCCESS';
// export const OPEN_VIEW_TRAINERS_GENERALRATING_BYMEMBER_MODEL = 'OPEN_VIEW_TRAINERS_GENERALRATING_BYMEMBER_MODEL';
// export const OPEN_VIEW_TRAINERS_GENERALRATING_BYMEMBER_MODEL_SUCCESS = 'OPEN_VIEW_TRAINERS_GENERALRATING_BYMEMBER_MODEL_SUCCESS';
// export const CLOSE_VIEW_TRAINERS_GENERALRATING_BYMEMBER_MODEL = 'CLOSE_VIEW_TRAINERS_GENERALRATING_BYMEMBER_MODEL';
//
// //product
// export const OPEN_ADD_NEW_PRODUCT_MODEL = 'OPEN_ADD_NEW_PRODUCT_MODEL';
// export const OPEN_ADD_NEW_PRODUCT_MODEL_SUCCESS = 'OPEN_ADD_NEW_PRODUCT_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_PRODUCT_MODEL = 'CLOSE_ADD_NEW_PRODUCT_MODEL';
// export const SAVE_PRODUCT = 'SAVE_PRODUCT';
// export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS';
// export const GET_PRODUCTS = 'GET_PRODUCTS';
// export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
// export const OPEN_EDIT_PRODUCT_MODEL = 'OPEN_EDIT_PRODUCT_MODEL';
// export const OPEN_EDIT_PRODUCT_MODEL_SUCCESS = 'OPEN_EDIT_PRODUCT_MODEL_SUCCESS';
// export const OPEN_VIEW_PRODUCT_MODEL = 'OPEN_VIEW_PRODUCT_MODEL';
// export const OPEN_VIEW_PRODUCT_MODEL_SUCCESS = 'OPEN_VIEW_PRODUCT_MODEL_SUCCESS';
// export const CLOSE_VIEW_PRODUCT_MODEL = 'CLOSE_VIEW_PRODUCT_MODEL';
// export const DELETE_PRODUCT = 'DELETE_PRODUCT';
// export const ADD_PRODUCT_QUANTITY = 'ADD_PRODUCT_QUANTITY';
//
// //equipment
// export const OPEN_ADD_NEW_EQUIPMENT_MODEL = 'OPEN_ADD_NEW_EQUIPMENT_MODEL';
// export const CLOSE_ADD_NEW_EQUIPMENT_MODEL = 'CLOSE_ADD_NEW_EQUIPMENT_MODEL';
// export const SAVE_EQUIPMENT = 'SAVE_EQUIPMENT';
// export const SAVE_EQUIPMENT_SUCCESS = 'SAVE_EQUIPMENT_SUCCESS';
// export const GET_EQUIPMENT = 'GET_EQUIPMENT';
// export const GET_EQUIPMENT_SUCCESS = 'GET_EQUIPMENT_SUCCESS';
// export const OPEN_VIEW_EQUIPMENT_MODEL = 'OPEN_VIEW_EQUIPMENT_MODEL';
// export const OPEN_VIEW_EQUIPMENT_MODEL_SUCCESS = 'OPEN_VIEW_EQUIPMENT_MODEL_SUCCESS';
// export const CLOSE_VIEW_EQUIPMENT_MODEL = 'CLOSE_VIEW_EQUIPMENT_MODEL';
// export const OPEN_EDIT_EQUIPMENT_MODEL = 'OPEN_EDIT_EQUIPMENT_MODEL';
// export const OPEN_EDIT_EQUIPMENT_MODEL_SUCCESS = 'OPEN_EDIT_EQUIPMENT_MODEL_SUCCESS';
// export const DELETE_EQUIPMENT = 'DELETE_EQUIPMENT';
//
//
// //broadcast
// export const OPEN_ADD_NEW_BROADCAST_MODEL = 'OPEN_ADD_NEW_BROADCAST_MODEL';
// export const OPEN_ADD_NEW_BROADCAST_MODEL_SUCCESS = 'OPEN_ADD_NEW_BROADCAST_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_BROADCAST_MODEL = 'CLOSE_ADD_NEW_BROADCAST_MODEL';
// export const SAVE_BROADCAST = 'SAVE_BROADCAST';
// export const SAVE_BROADCAST_SUCCESS = 'SAVE_BROADCAST_SUCCESS';
// export const GET_BROADCAST = 'GET_BROADCAST';
// export const GET_BROADCAST_SUCCESS = 'GET_BROADCAST_SUCCESS';
// export const OPEN_VIEW_BROADCAST_MODEL = 'OPEN_VIEW_BROADCAST_MODEL';
// export const OPEN_VIEW_BROADCAST_MODEL_SUCCESS = 'OPEN_VIEW_BROADCAST_MODEL_SUCCESS';
// export const CLOSE_VIEW_BROADCAST_MODEL = 'CLOSE_VIEW_BROADCAST_MODEL';
//
//
// export const GET_EQUIPMENT_INSTOCK = 'GET_EQUIPMENT_INSTOCK';
// export const GET_EQUIPMENT_INSTOCK_SUCCESS = 'GET_EQUIPMENT_INSTOCK_SUCCESS';
// export const OPEN_VIEW_EQUIPMENT_INSTOCK_MODEL = 'OPEN_VIEW_EQUIPMENT_INSTOCK_MODEL';
// export const OPEN_VIEW_EQUIPMENT_INSTOCK_MODEL_SUCCESS = 'OPEN_VIEW_EQUIPMENT_INSTOCK_MODEL_SUCCESS';
// export const CLOSE_VIEW_EQUIPMENT_INSTOCK_MODEL = 'CLOSE_VIEW_EQUIPMENT_INSTOCK_MODEL';
//
// export const OPEN_VIEW_EQUIPMENT_INSTOCK_MAINTENANCE_MODEL = 'OPEN_VIEW_EQUIPMENT_INSTOCK_MAINTENANCE_MODEL';
// export const OPEN_VIEW_EQUIPMENT_INSTOCK_MAINTENANCE_MODEL_SUCCESS = 'OPEN_VIEW_EQUIPMENT_INSTOCK_MAINTENANCE_MODEL_SUCCESS';
// export const CLOSE_VIEW_EQUIPMENT_INSTOCK_MAINTENANCE_MODEL = 'CLOSE_VIEW_EQUIPMENT_INSTOCK_MAINTENANCE_MODEL';
// export const SAVE_EQUIPMENT_INSTOCK_MAINTENANCE = 'SAVE_EQUIPMENT_INSTOCK_MAINTENANCE';
// export const SAVE_EQUIPMENT_INSTOCK_MAINTENANCE_SUCCESS = 'SAVE_EQUIPMENT_INSTOCK_MAINTENANCE_SUCCESS';
//
// export const GET_EQUIPMENT_PURCHASED = 'GET_EQUIPMENT_PURCHASED';
// export const GET_EQUIPMENT_PURCHASED_SUCCESS = 'GET_EQUIPMENT_PURCHASED_SUCCESS';
// export const OPEN_VIEW_EQUIPMENT_PURCHASED_MODEL = 'OPEN_VIEW_EQUIPMENT_PURCHASED_MODEL';
// export const OPEN_VIEW_EQUIPMENT_PURCHASED_MODEL_SUCCESS = 'OPEN_VIEW_EQUIPMENT_PURCHASED_MODEL_SUCCESS';
// export const CLOSE_VIEW_EQUIPMENT_PURCHASED_MODEL = 'CLOSE_VIEW_EQUIPMENT_PURCHASED_MODEL';
// export const OPEN_EDIT_EQUIPMENT_PURCHASED_MODEL = 'OPEN_EDIT_EQUIPMENT_PURCHASED_MODEL';
// export const OPEN_EDIT_EQUIPMENT_PURCHASED_MODEL_SUCCESS = 'OPEN_EDIT_EQUIPMENT_PURCHASED_MODEL_SUCCESS';
// export const OPEN_ADD_NEW_EQUIPMENT_PURCHASED_MODEL = 'OPEN_ADD_NEW_EQUIPMENT_PURCHASED_MODEL';
// export const CLOSE_ADD_NEW_EQUIPMENT_PURCHASED_MODEL = 'CLOSE_ADD_NEW_EQUIPMENT_PURCHASED_MODEL';
// export const SAVE_EQUIPMENT_PURCHASED = 'SAVE_EQUIPMENT_PURCHASED';
// export const SAVE_EQUIPMENT_PURCHASED_SUCCESS = 'SAVE_EQUIPMENT_PURCHASED_SUCCESS';
// export const DELETE_EQUIPMENT_PURCHASED = 'DELETE_EQUIPMENT_PURCHASED';
//
// export const OPEN_ADD_NEW_EQUIPMENT_BRAND_MODEL = 'OPEN_ADD_NEW_EQUIPMENT_BRAND_MODEL';
// export const CLOSE_ADD_NEW_EQUIPMENT_BRAND_MODEL = 'CLOSE_ADD_NEW_EQUIPMENT_BRAND_MODEL';
// export const SAVE_EQUIPMENT_BRAND = 'SAVE_EQUIPMENT_BRAND';
// export const SAVE_EQUIPMENT_BRAND_SUCCESS = 'SAVE_EQUIPMENT_BRAND_SUCCESS';
// export const GET_EQUIPMENT_BRAND = 'GET_EQUIPMENT_BRAND';
// export const GET_EQUIPMENT_BRAND_SUCCESS = 'GET_EQUIPMENT_BRAND_SUCCESS';
// export const OPEN_EDIT_EQUIPMENT_BRAND_MODEL = 'OPEN_EDIT_EQUIPMENT_BRAND_MODEL';
// export const DELETE_EQUIPMENT_BRAND = 'DELETE_EQUIPMENT_BRAND';
//
//
// //expense
// export const OPEN_ADD_NEW_EXPENSE_MODEL = 'OPEN_ADD_NEW_EXPENSE_MODEL';
// export const OPEN_ADD_NEW_EXPENSE_MODEL_SUCCESS = 'OPEN_ADD_NEW_EXPENSE_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_EXPENSE_MODEL = 'CLOSE_ADD_NEW_EXPENSE_MODEL';
// export const SAVE_EXPENSE = 'SAVE_EXPENSE';
// export const SAVE_EXPENSE_SUCCESS = 'SAVE_EXPENSE_SUCCESS';
// export const GET_EXPENSE = 'GET_EXPENSE';
// export const GET_EXPENSE_SUCCESS = 'GET_EXPENSE_SUCCESS';
// export const OPEN_EDIT_EXPENSE_MODEL = 'OPEN_EDIT_EXPENSE_MODEL';
// export const OPEN_EDIT_EXPENSE_MODEL_SUCCESS = 'OPEN_EDIT_EXPENSE_MODEL_SUCCESS';
// export const OPEN_VIEW_EXPENSE_MODEL = 'OPEN_VIEW_EXPENSE_MODEL';
// export const OPEN_VIEW_EXPENSE_MODEL_SUCCESS = 'OPEN_VIEW_EXPENSE_MODEL_SUCCESS';
// export const CLOSE_VIEW_EXPENSE_MODEL = 'CLOSE_VIEW_EXPENSE_MODEL';
// export const DELETE_EXPENSE = 'DELETE_EXPENSE';
//
// export const OPEN_CLAIM_EXPENSE_MODEL = 'OPEN_CLAIM_EXPENSE_MODEL';
// export const OPEN_CLAIM_EXPENSE_MODEL_SUCCESS = 'OPEN_CLAIM_EXPENSE_MODEL_SUCCESS';
// export const CLOSE_CLAIM_EXPENSE_MODEL = 'CLOSE_CLAIM_EXPENSE_MODEL';
// export const SAVE_CLAIM_EXPENSE = 'SAVE_CLAIM_EXPENSE';
// export const SAVE_CLAIM_EXPENSE_SUCCESS = 'SAVE_CLAIM_EXPENSE_SUCCESS';
//
// export const EXPENSE_SETTLEMENT = 'EXPENSE_SETTLEMENT';
//
// export const IMPORT_EXPENSE = 'IMPORT_EXPENSE';
// export const IMPORT_EXPENSE_SUCCESS = 'IMPORT_EXPENSE_SUCCESS';
// export const IMPORT_EXPENSE_LIST = 'IMPORT_EXPENSE_LIST';
// export const IMPORT_EXPENSE_LIST_SUCCESS = 'IMPORT_EXPENSE_LIST_SUCCESS';
//
//
// //investment
// export const OPEN_ADD_NEW_INVESTMENT_MODEL = 'OPEN_ADD_NEW_INVESTMENT_MODEL';
// export const CLOSE_ADD_NEW_INVESTMENT_MODEL = 'CLOSE_ADD_NEW_INVESTMENT_MODEL';
// export const SAVE_INVESTMENT = 'SAVE_INVESTMENT';
// export const SAVE_INVESTMENT_SUCCESS = 'SAVE_INVESTMENT_SUCCESS';
// export const GET_INVESTMENTS = 'GET_INVESTMENTS';
// export const GET_INVESTMENTS_SUCCESS = 'GET_INVESTMENTS_SUCCESS';
// export const OPEN_VIEW_INVESTMENT_MODEL = 'OPEN_VIEW_INVESTMENT_MODEL';
// export const OPEN_VIEW_INVESTMENT_MODEL_SUCCESS = 'OPEN_VIEW_INVESTMENT_MODEL_SUCCESS';
// export const CLOSE_VIEW_INVESTMENT_MODEL = 'CLOSE_VIEW_INVESTMENT_MODEL';
// export const DELETE_INVESTMENT = 'DELETE_INVESTMENT';
//
//
// //staffpay
// export const OPEN_ADD_NEW_STAFFPAY_MODEL = 'OPEN_ADD_NEW_STAFFPAY_MODEL';
// export const OPEN_ADD_NEW_STAFFPAY_MODEL_SUCCESS = 'OPEN_ADD_NEW_STAFFPAY_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_STAFFPAY_MODEL = 'CLOSE_ADD_NEW_STAFFPAY_MODEL';
// export const SAVE_STAFFPAY = 'SAVE_STAFFPAY';
// export const SAVE_STAFFPAY_SUCCESS = 'SAVE_STAFFPAY_SUCCESS';
// export const GET_STAFFPAY = 'GET_STAFFPAY';
// export const GET_STAFFPAY_SUCCESS = 'GET_STAFFPAY_SUCCESS';
// export const OPEN_VIEW_STAFFPAY_MODEL = 'OPEN_VIEW_STAFFPAY_MODEL';
// export const OPEN_VIEW_STAFFPAY_MODEL_SUCCESS = 'OPEN_VIEW_STAFFPAY_MODEL_SUCCESS';
// export const CLOSE_VIEW_STAFFPAY_MODEL = 'CLOSE_VIEW_STAFFPAY_MODEL';
// export const DELETE_STAFFPAY = 'DELETE_STAFFPAY';
//
//
// //exercise
// export const OPEN_ADD_NEW_EXERCISE_MODEL = 'OPEN_ADD_NEW_EXERCISE_MODEL';
// export const CLOSE_ADD_NEW_EXERCISE_MODEL = 'CLOSE_ADD_NEW_EXERCISE_MODEL';
// export const SAVE_EXERCISE = 'SAVE_EXERCISE';
// export const SAVE_EXERCISE_SUCCESS = 'SAVE_EXERCISE_SUCCESS';
// export const GET_EXERCISES = 'GET_EXERCISES';
// export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
// export const OPEN_EDIT_EXERCISES_MODEL = 'OPEN_EDIT_EXERCISES_MODEL';
// export const OPEN_EDIT_EXERCISES_MODEL_SUCCESS = 'OPEN_EDIT_EXERCISES_MODEL_SUCCESS';
// export const OPEN_VIEW_EXERCISES_MODEL = 'OPEN_VIEW_EXERCISES_MODEL';
// export const OPEN_VIEW_EXERCISES_MODEL_SUCCESS = 'OPEN_VIEW_EXERCISES_MODEL_SUCCESS';
// export const CLOSE_VIEW_EXERCISES_MODEL = 'CLOSE_VIEW_EXERCISES_MODEL';
// export const DELETE_EXERCISES = 'DELETE_EXERCISES';
// export const SAVE_FAVORITE_EXERCISE = 'SAVE_FAVORITE_EXERCISE';
// export const SAVE_FAVORITE_EXERCISE_SUCCESS = 'SAVE_FAVORITE_EXERCISE_SUCCESS';
// export const SAVE_FAVORITE_EXERCISE_FAILURE = 'SAVE_FAVORITE_EXERCISE_FAILURE';
//
//
// //workout routine
//
// export const OPEN_ADD_NEW_WORKOUTROUTINE_MODEL = 'OPEN_ADD_NEW_WORKOUTROUTINE_MODEL';
// export const CLOSE_ADD_NEW_WORKOUTROUTINE_MODEL = 'CLOSE_ADD_NEW_WORKOUTROUTINE_MODEL';
// export const SAVE_WORKOUTROUTINE = 'SAVE_WORKOUTROUTINE';
// export const SAVE_WORKOUTROUTINE_SUCCESS = 'SAVE_WORKOUTROUTINE_SUCCESS';
// export const GET_WORKOUTROUTINES = 'GET_WORKOUTROUTINES';
// export const GET_WORKOUTROUTINE_SUCCESS = 'GET_WORKOUTROUTINE_SUCCESS';
// export const OPEN_EDIT_WORKOUTROUTINE_MODEL = 'OPEN_EDIT_WORKOUTROUTINE_MODEL';
// export const OPEN_EDIT_WORKOUTROUTINE_MODEL_SUCCESS = 'OPEN_EDIT_WORKOUTROUTINE_MODEL_SUCCESS';
// export const OPEN_VIEW_WORKOUTROUTINE_MODEL = 'OPEN_VIEW_WORKOUTROUTINE_MODEL';
// export const OPEN_VIEW_WORKOUTROUTINE_MODEL_SUCCESS = 'OPEN_VIEW_WORKOUTROUTINE_MODEL_SUCCESS';
// export const CLOSE_VIEW_WORKOUTROUTINE_MODEL = 'CLOSE_VIEW_WORKOUTROUTINE_MODEL';
// export const DELETE_WORKOUTROUTINE = 'DELETE_WORKOUTROUTINE';
//
// // workout routine day
// export const OPEN_ADD_NEW_WORKOUTROUTINEDAY_MODEL = 'OPEN_ADD_NEW_WORKOUTROUTINEDAY_MODEL';
// export const CLOSE_ADD_NEW_WORKOUTROUTINEDAY_MODEL = 'CLOSE_ADD_NEW_WORKOUTROUTINEDAY_MODEL';
// export const SAVE_WORKOUTROUTINEDAY = 'SAVE_WORKOUTROUTINEDAY';
// export const SAVE_WORKOUTROUTINEDAY_SUCCESS = 'SAVE_WORKOUTROUTINEDAY_SUCCESS';
// export const OPEN_EDIT_WORKOUTROUTINEDAY_MODEL = 'OPEN_EDIT_WORKOUTROUTINEDAY_MODEL';
// export const OPEN_EDIT_WORKOUTROUTINEDAY_MODEL_SUCCESS = 'OPEN_EDIT_WORKOUTROUTINEDAY_MODEL_SUCCESS';
// export const DELETE_WORKOUTROUTINEDAY = 'DELETE_WORKOUTROUTINEDAY';
// export const SAVE_WORKOUEXERCISE = 'SAVE_WORKOUEXERCISE';
// export const SAVE_WORKOUTEXERCISE_SUCCESS = 'SAVE_WORKOUTEXERCISE_SUCCESS';
//
// // member attendance
// export const SAVE_MEMBERATTENDANCE = 'SAVE_MEMBERATTENDANCE';
// export const SAVE_MEMBERATTENDANCE_SUCCESS = 'SAVE_MEMBERATTENDANCE_SUCCESS';
//
// export const GET_MEMBERATTENDANCE_LIST = 'GET_MEMBERATTENDANCE_LIST';
// export const GET_MEMBERATTENDANCE_LIST_SUCCESS = 'GET_MEMBERATTENDANCE_LIST_SUCCESS';
// export const DELETE_ATTENDANCE = 'DELETE_ATTENDANCE';
// export const DELETE_LAST_ATTENDANCE = 'DELETE_LAST_ATTENDANCE';
//
// //member pt attendence
// export const SAVE_MEMBER_PT_ATTENDANCE = 'SAVE_MEMBER_PT_ATTENDANCE';
// export const SAVE_MEMBER_PT_ATTENDANCE_SUCCESS = 'SAVE_MEMBER_PT_ATTENDANCE_SUCCESS';
// export const GET_MEMBER_PT_ATTENDANCE_LIST = 'GET_MEMBER_PT_ATTENDANCE_LIST';
// export const GET_MEMBER_PT_ATTENDANCE_LIST_SUCCESS = 'GET_MEMBER_PT_ATTENDANCE_LIST_SUCCESS';
// export const DELETE_PT_ATTENDANCE = 'DELETE_PT_ATTENDANCE';
// export const DELETE_LAST_PT_ATTENDANCE = 'DELETE_LAST_PT_ATTENDANCE';
// export const SAVE_PT_SESSIONTIMEWEIGHT = 'SAVE_PT_SESSIONTIMEWEIGHT';
// export const SAVE_PT_SESSIONTIMEWEIGHT_SUCCESS = 'SAVE_PT_SESSIONTIMEWEIGHT_SUCCESS';
//
//
// // employee  attendance
// export const SAVE_EMPLOYEEATTENDANCE = 'SAVE_EMPLOYEEATTENDANCE';
// export const SAVE_EMPLOYEEATTENDANCE_SUCCESS = 'SAVE_EMPLOYEEATTENDANCE_SUCCESS';
// export const GET_EMPLOYEEATTENDANCE_LIST = 'GET_EMPLOYEEATTENDANCE_LIST';
// export const GET_EMPLOYEEATTENDANCE_LIST_SUCCESS = 'GET_EMPLOYEEATTENDANCE_LIST_SUCCESS';
// export const DELETE_EMPLOYEE_ATTENDANCE = 'DELETE_EMPLOYEE_ATTENDANCE';
// export const DELETE_EMPLOYEE_LAST_ATTENDANCE = 'DELETE_EMPLOYEE_LAST_ATTENDANCE';
//
// // workout SCHEDULE
// export const OPEN_ADD_NEW_WORKOUTSCHEDULE_MODEL = 'OPEN_ADD_NEW_WORKOUTSCHEDULE_MODEL';
// export const OPEN_ADD_NEW_WORKOUTSCHEDULE_MODEL_SUCCESS = 'OPEN_ADD_NEW_WORKOUTSCHEDULE_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_WORKOUTSCHEDULE_MODEL = 'CLOSE_ADD_NEW_WORKOUTSCHEDULE_MODEL';
// export const SAVE_WORKOUTSCHEDULE = 'SAVE_WORKOUTSCHEDULE';
// export const SAVE_WORKOUTSCHEDULE_SUCCESS = 'SAVE_WORKOUTSCHEDULE_SUCCESS';
// export const GET_WORKOUTSCHEDULES = 'GET_WORKOUTSCHEDULES';
// export const GET_WORKOUTSCHEDULE_SUCCESS = 'GET_WORKOUTSCHEDULE_SUCCESS';
// export const OPEN_EDIT_WORKOUTSCHEDULE_MODEL = 'OPEN_EDIT_WORKOUTSCHEDULE_MODEL';
// export const OPEN_EDIT_WORKOUTSCHEDULE_MODEL_SUCCESS = 'OPEN_EDIT_WORKOUTSCHEDULE_MODEL_SUCCESS';
// export const OPEN_VIEW_WORKOUTSCHEDULE_MODEL = 'OPEN_VIEW_WORKOUTSCHEDULE_MODEL';
// export const OPEN_VIEW_WORKOUTSCHEDULE_MODEL_SUCCESS = 'OPEN_VIEW_WORKOUTSCHEDULE_MODEL_SUCCESS';
// export const CLOSE_VIEW_WORKOUTSCHEDULE_MODEL = 'CLOSE_VIEW_WORKOUTSCHEDULE_MODEL';
// export const DELETE_WORKOUTSCHEDULE = 'DELETE_WORKOUTSCHEDULE';
// export const SAVE_PHASE = 'SAVE_PHASE';
// export const SAVE_PHASE_SUCCESS = 'SAVE_PHASE_SUCCESS';
// export const OPEN_ADD_NEW_ALLOCATED_MEMBER_MODEL = 'OPEN_ADD_NEW_ALLOCATED_MEMBER_MODEL';
// export const CLOSE_ADD_NEW_ALLOCATED_MEMBER_MODEL = 'CLOSE_ADD_NEW_ALLOCATED_MEMBER_MODEL';
// export const OPEN_FILTER_WITH_WORKOUTENDDATE_MEMBER_MODEL = 'OPEN_FILTER_WITH_WORKOUTENDDATE_MEMBER_MODEL';
// export const CLOSE_FILTER_WITH_WORKOUTENDDATE_MEMBER_MODEL = 'CLOSE_FILTER_WITH_WORKOUTENDDATE_MEMBER_MODEL';
// export const ON_NOTALLOCATEDMEMBERFILTER_CHANGE = 'ON_NOTALLOCATEDMEMBERFILTER_CHANGE';
//
// // Template Configuration
// export const OPEN_ADD_NEW_TEMPLTECONFIGURATION_MODEL = 'OPEN_ADD_NEW_TEMPLTECONFIGURATION_MODEL';
// export const CLOSE_ADD_NEW_TEMPLTECONFIGURATION_MODEL = 'CLOSE_ADD_NEW_TEMPLTECONFIGURATION_MODEL';
// export const SAVE_TEMPLTECONFIGURATION = 'SAVE_TEMPLTECONFIGURATION';
// export const SAVE_TEMPLTECONFIGURATION_SUCCESS = 'SAVE_TEMPLTECONFIGURATION_SUCCESS';
// export const GET_TEMPLTECONFIGURATIONS = 'GET_TEMPLTECONFIGURATIONS';
// export const GET_TEMPLTECONFIGURATION_SUCCESS = 'GET_TEMPLTECONFIGURATION_SUCCESS';
// export const OPEN_EDIT_TEMPLTECONFIGURATION_MODEL = 'OPEN_EDIT_TEMPLTECONFIGURATION_MODEL';
// export const OPEN_EDIT_TEMPLTECONFIGURATION_MODEL_SUCCESS = 'OPEN_EDIT_TEMPLTECONFIGURATION_MODEL_SUCCESS';
// export const OPEN_VIEW_TEMPLTECONFIGURATION_MODEL = 'OPEN_VIEW_TEMPLTECONFIGURATION_MODEL';
// export const OPEN_VIEW_TEMPLTECONFIGURATION_MODEL_SUCCESS = 'OPEN_VIEW_TEMPLTECONFIGURATION_MODEL_SUCCESS';
// export const CLOSE_VIEW_TEMPLTECONFIGURATION_MODEL = 'CLOSE_VIEW_TEMPLTECONFIGURATION_MODEL';
// export const DELETE_TEMPLTECONFIGURATION = 'DELETE_TEMPLTECONFIGURATION';
//
// //Notification configurationType
// export const SAVE_NOTIFICATION_CONFIGURATION = 'SAVE_NOTIFICATION_CONFIGURATION';
// export const SAVE_NOTIFICATION_CONFIGURATION_SUCCESS = 'SAVE_NOTIFICATION_CONFIGURATION_SUCCESS';
// export const VIEW_NOTIFICATION_CONFIGURATION = 'VIEW_NOTIFICATION_CONFIGURATION';
// export const VIEW_NOTIFICATION_CONFIGURATION_SUCCESS = 'VIEW_NOTIFICATION_CONFIGURATION_SUCCESS';
// export const SAVE_NOTIFICATION_EMAIL_GATEWAY = 'SAVE_NOTIFICATION_EMAIL_GATEWAY';
// export const SAVE_NOTIFICATION_EMAIL_GATEWAY_SUCCESS = 'SAVE_NOTIFICATION_EMAIL_GATEWAY_SUCCESS';
// export const VIEW_NOTIFICATION_GATEWAY_INFORMATION = 'VIEW_NOTIFICATION_GATEWAY_INFORMATION';
// export const VIEW_NOTIFICATION_GATEWAY_INFORMATION_SUCCESS = 'VIEW_NOTIFICATION_GATEWAY_INFORMATION_SUCCESS';
//
// // class attendance
// export const SAVE_CLASSATTENDANCE = 'SAVE_CLASSATTENDANCE';
// export const SAVE_CLASSATTENDANCE_SUCCESS = 'SAVE_CLASSATTENDANCE_SUCCESS';
//
// export const GET_CLASSATTENDANCE_LIST = 'GET_CLASSATTENDANCE_LIST';
// export const GET_CLASSATTENDANCE_LIST_SUCCESS = 'GET_CLASSATTENDANCE_LIST_SUCCESS';
//
// export const DELETE_CLASS_ATTENDANCE = 'DELETE_CLASS_ATTENDANCE';
// export const DELETE_CLASS_LAST_ATTENDANCE = 'DELETE_LAST_ATTENDANCE';
//
// export const SAVE_SESSIONWEIGHT = 'SAVE_SESSIONWEIGHT';
// export const SAVE_SESSIONWEIGHT_SUCCESS = 'SAVE_SESSIONWEIGHT_SUCCESS';
//
// role
export const OPEN_ADD_NEW_ROLE_MODEL = 'OPEN_ADD_NEW_ROLE_MODEL';
export const OPEN_ADD_NEW_ROLE_MODEL_SUCCESS = 'OPEN_ADD_NEW_ROLE_MODEL_SUCCESS';
export const CLOSE_ADD_NEW_ROLE_MODEL = 'CLOSE_ADD_NEW_ROLE_MODEL';
export const SAVE_ROLE = 'SAVE_ROLE';
export const SAVE_ROLE_SUCCESS = 'SAVE_ROLE_SUCCESS';
export const GET_ROLES = 'GET_ROLES';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const OPEN_EDIT_ROLE_MODEL = 'OPEN_EDIT_ROLE_MODEL';
export const DELETE_ROLE = 'DELETE_ROLE';
//
// // recipe
//
// export const OPEN_ADD_NEW_RECIPE_MODEL = 'OPEN_ADD_NEW_RECIPE_MODEL';
// export const CLOSE_ADD_NEW_RECIPE_MODEL = 'CLOSE_ADD_NEW_RECIPE_MODEL';
// export const SAVE_RECIPE = 'SAVE_RECIPE';
// export const SAVE_RECIPE_SUCCESS = 'SAVE_RECIPE_SUCCESS';
// export const GET_RECIPES = 'GET_RECIPES';
// export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
// export const OPEN_EDIT_RECIPES_MODEL = 'OPEN_EDIT_RECIPES_MODEL';
// export const OPEN_EDIT_RECIPES_MODEL_SUCCESS = 'OPEN_EDIT_RECIPES_MODEL_SUCCESS';
// export const OPEN_VIEW_RECIPES_MODEL = 'OPEN_VIEW_RECIPES_MODEL';
// export const OPEN_VIEW_RECIPES_MODEL_SUCCESS = 'OPEN_VIEW_RECIPES_MODEL_SUCCESS';
// export const CLOSE_VIEW_RECIPES_MODEL = 'CLOSE_VIEW_RECIPES_MODEL';
// export const DELETE_RECIPE = 'DELETE_RECIPE';
//
// //gym rule
//
// export const OPEN_ADD_NEW_RULE_MODEL = 'OPEN_ADD_NEW_RULE_MODEL';
// export const CLOSE_ADD_NEW_RULE_MODEL = 'CLOSE_ADD_NEW_RULE_MODEL';
// export const SAVE_RULE = 'SAVE_RULE';
// export const SAVE_RULE_SUCCESS = 'SAVE_RULE_SUCCESS';
// export const GET_RULES = 'GET_RULES';
// export const GET_RULES_SUCCESS = 'GET_RULES_SUCCESS';
// export const OPEN_EDIT_RULE_MODEL = 'OPEN_EDIT_RULE_MODEL';
// export const DELETE_RULE = 'DELETE_RULE';
//
// //questions
//
// export const OPEN_ADD_NEW_QUESTION_MODEL = 'OPEN_ADD_NEW_QUESTION_MODEL';
// export const CLOSE_ADD_NEW_QUESTION_MODEL = 'CLOSE_ADD_NEW_QUESTION_MODEL';
// export const SAVE_QUESTION = 'SAVE_QUESTION';
// export const SAVE_QUESTION_SUCCESS = 'SAVE_QUESTION_SUCCESS';
// export const GET_QUESTIONS = 'GET_QUESTIONS';
// export const GET_QUESTIONS_SUCCESS = 'GET_QUESTIONS_SUCCESS';
// export const OPEN_EDIT_QUESTION_MODEL = 'OPEN_EDIT_QUESTION_MODEL';
// export const DELETE_QUESTION = 'DELETE_QUESTION';
//
// export const VIEW_DISCLAIMER = 'VIEW_DISCLAIMER';
// export const VIEW_DISCLAIMER_SUCCESS = 'VIEW_DISCLAIMER_SUCCESS';
// export const SAVE_DISCLAIMER = 'SAVE_DISCLAIMER';
//
// export const VIEW_COVID19_DISCLAIMER = 'VIEW_COVID19_DISCLAIMER';
// export const VIEW_COVID19_DISCLAIMER_SUCCESS = 'VIEW_COVID19_DISCLAIMER_SUCCESS';
// export const SAVE_COVID19_DISCLAIMER = 'SAVE_COVID19_DISCLAIMER';
//
// export const GET_MEMBER_COVID19DISCLAIMERFORM = 'GET_MEMBER_COVID19DISCLAIMERFORM';
// export const GET_MEMBER_COVID19DISCLAIMERFORM_SUCCESS = 'GET_MEMBER_COVID19DISCLAIMERFORM_SUCCESS';
// export const GET_STAFF_COVID19DISCLAIMERFORM = 'GET_STAFF_COVID19DISCLAIMERFORM';
// export const GET_STAFF_COVID19DISCLAIMERFORM_SUCCESS = 'GET_STAFF_COVID19DISCLAIMERFORM_SUCCESS';
//
// export const OPEN_STAFF_COVID19DISCLAIMER_MODEL = 'OPEN_STAFF_COVID19DISCLAIMER_MODEL';
// export const OPEN_STAFF_COVID19DISCLAIMER_MODEL_SUCCESS = 'OPEN_STAFF_COVID19DISCLAIMER_MODEL_SUCCESS';
// export const CLOSE_STAFF_COVID19DISCLAIMER_MODEL = 'CLOSE_STAFF_COVID19DISCLAIMER_MODEL';
// export const SAVE_STAFF_COVID19DISCLAIMER = 'SAVE_STAFF_COVID19DISCLAIMER';
// export const SAVE_STAFF_COVID19DISCLAIMER_SUCCESS = 'SAVE_STAFF_COVID19DISCLAIMER_SUCCESS';
//
// export const OPEN_STAFFDISCLAIMER_MODEL = 'OPEN_STAFFDISCLAIMER_MODEL';
// export const OPEN_STAFFDISCLAIMER_MODEL_SUCCESS = 'OPEN_STAFFDISCLAIMER_MODEL_SUCCESS';
// export const CLOSE_STAFFDISCLAIMER_MODEL = 'CLOSE_STAFFDISCLAIMER_MODEL';
// export const SAVE_STAFFDISCLAIMER = 'SAVE_STAFFDISCLAIMER';
// export const SAVE_STAFFDISCLAIMER_SUCCESS = 'SAVE_STAFFDISCLAIMER_SUCCESS';
// export const GET_STAFFDISCLAIMER_SAVED_FORM = 'GET_STAFFDISCLAIMER_SAVED_FORM';
// export const GET_STAFFDISCLAIMER_SAVED_FORM_SUCCESS = 'GET_STAFFDISCLAIMER_SAVED_FORM_SUCCESS';
//
//
// // diet routine
// export const OPEN_ADD_NEW_DIET_ROUTINE_MODEL = 'OPEN_ADD_NEW_DIET_ROUTINE_MODEL';
// export const CLOSE_ADD_NEW_DIET_ROUTINE_MODEL = 'CLOSE_ADD_NEW_DIET_ROUTINE_MODEL';
// export const SAVE_DIET_ROUTINE = 'SAVE_DIET_ROUTINE';
// export const SAVE_DIET_ROUTINE_SUCCESS = 'SAVE_DIET_ROUTINE_SUCCESS';
// export const GET_DIET_ROUTINES = 'GET_DIET_ROUTINES';
// export const GET_DIET_ROUTINES_SUCCESS = 'GET_DIET_ROUTINES_SUCCESS';
// export const OPEN_EDIT_DIET_ROUTINE_MODEL = 'OPEN_EDIT_DIET_ROUTINE_MODEL';
// export const OPEN_EDIT_DIET_ROUTINE_MODEL_SUCCESS = 'OPEN_EDIT_DIET_ROUTINE_MODEL_SUCCESS';
// export const OPEN_VIEW_DIET_ROUTINE_MODEL = 'OPEN_VIEW_DIET_ROUTINE_MODEL';
// export const OPEN_VIEW_DIET_ROUTINE_MODEL_SUCCESS = 'OPEN_VIEW_DIET_ROUTINE_MODEL_SUCCESS';
// export const CLOSE_VIEW_DIET_ROUTINE_MODEL = 'CLOSE_VIEW_DIET_ROUTINE_MODEL';
// export const DELETE_DIET_ROUTINE = 'DELETE_DIET_ROUTINE';
//
//
// // allocate diet
// export const OPEN_ADD_NEW_ALLOCATEDIET_MODEL = 'OPEN_ADD_NEW_ALLOCATEDIET_MODEL';
// export const CLOSE_ADD_NEW_ALLOCATEDIET_MODEL = 'CLOSE_ADD_NEW_ALLOCATEDIET_MODEL';
// export const SAVE_ALLOCATEDIET = 'SAVE_ALLOCATEDIET';
// export const SAVE_ALLOCATEDIET_SUCCESS = 'SAVE_ALLOCATEDIET_SUCCESS';
// export const GET_ALLOCATEDIETS = 'GET_ALLOCATEDIETS';
// export const GET_ALLOCATEDIET_SUCCESS = 'GET_ALLOCATEDIET_SUCCESS';
// export const SAVE_DIET_PHASE = 'SAVE_DIET_PHASE';
// export const OPEN_EDIT_ALLOCATEDIET_MODEL = 'OPEN_EDIT_ALLOCATEDIET_MODEL';
// export const OPEN_EDIT_ALLOCATEDIET_MODEL_SUCCESS = 'OPEN_EDIT_ALLOCATEDIET_MODEL_SUCCESS';
// export const OPEN_VIEW_ALLOCATEDIET_MODEL = 'OPEN_VIEW_ALLOCATEDIET_MODEL';
// export const OPEN_VIEW_ALLOCATEDIET_MODEL_SUCCESS = 'OPEN_VIEW_ALLOCATEDIET_MODEL_SUCCESS';
// export const CLOSE_VIEW_ALLOCATEDIET_MODEL = 'CLOSE_VIEW_ALLOCATEDIET_MODEL';
// export const DELETE_ALLOCATEDIET = 'DELETE_ALLOCATEDIET';
// export const ON_DIETNOTALLOCATEDMEMBERFILTER_CHANGE = 'ON_DIETNOTALLOCATEDMEMBERFILTER_CHANGE';
// export const OPEN_ADD_NEW_DIET_NOT_ALLOCATED_MEMBER_MODEL = 'OPEN_ADD_NEW_DIET_NOT_ALLOCATED_MEMBER_MODEL';
// export const CLOSE_ADD_NEW_DIET_NOT_ALLOCATED_MEMBER_MODEL = 'CLOSE_ADD_NEW_DIET_NOT_ALLOCATED_MEMBER_MODEL';
// export const OPEN_FILTER_WITH_DIETENDDATE_MEMBER_MODEL = 'OPEN_FILTER_WITH_DIETENDDATE_MEMBER_MODEL';
// export const CLOSE_FILTER_WITH_DIETENDDATE_MEMBER_MODEL = 'CLOSE_FILTER_WITH_DIETENDDATE_MEMBER_MODEL';
//
//
// //biomax
// export const OPEN_VIEW_BIOMAX_MODEL = 'OPEN_VIEW_BIOMAX_MODEL';
// export const CLOSE_VIEW_BIOMAX_MODEL = 'CLOSE_VIEW_BIOMAX_MODEL';
// export const GET_BIOMAX_MEMBERS = 'GET_BIOMAX_MEMBERS';
// export const GET_BIOMAX_MEMBERS_SUCCESS = 'GET_BIOMAX_MEMBERS_SUCCESS';
// export const GET_BIOMAX_MEMBERS_LOGS = 'GET_BIOMAX_MEMBERS_LOGS';
// export const GET_BIOMAX_MEMBERS_LOGS_SUCCESS = 'GET_BIOMAX_MEMBERS_LOGS_SUCCESS';
//
// export const GET_BIOMAX_USERS = 'GET_BIOMAX_USERS';
// export const GET_BIOMAX_USERS_SUCCESS = 'GET_BIOMAX_USERS_SUCCESS';
// export const GET_BIOMAX_USERS_LOGS = 'GET_BIOMAX_USERS_LOGS';
// export const GET_BIOMAX_USERS_LOGS_SUCCESS = 'GET_BIOMAX_USERS_LOGS_SUCCESS';
//
// export const GET_BIOMAX_UNAUTHORISED_LOGS = 'GET_BIOMAX_UNAUTHORISED_LOGS';
// export const GET_BIOMAX_UNAUTHORISED_LOGS_SUCCESS = 'GET_BIOMAX_UNAUTHORISED_LOGS_SUCCESS';
//
// export const BIOMAX_HANDLE_CHANGE_SELECT_ALL = 'BIOMAX_HANDLE_CHANGE_SELECT_ALL';
// export const BIOMAX_HANDLE_SINGLE_CHECKBOX_CHANGE = 'BIOMAX_HANDLE_SINGLE_CHECKBOX_CHANGE';
//
// export const  USER_BIOMAX_HANDLE_CHANGE_SELECT_ALL = 'USER_BIOMAX_HANDLE_CHANGE_SELECT_ALL';
// export const  USER_BIOMAX_HANDLE_SINGLE_CHECKBOX_CHANGE = 'USER_BIOMAX_HANDLE_SINGLE_CHECKBOX_CHANGE';
//
//
// // budget
// export const OPEN_ADD_NEW_BUDGET_MODEL = 'OPEN_ADD_NEW_BUDGET_MODEL';
// export const CLOSE_ADD_NEW_BUDGET_MODEL = 'CLOSE_ADD_NEW_BUDGET_MODEL';
// export const SAVE_BUDGET = 'SAVE_BUDGET';
// export const SAVE_BUDGET_SUCCESS = 'SAVE_BUDGET_SUCCESS';
// export const GET_BUDGET = 'GET_BUDGET';
// export const GET_BUDGET_SUCCESS = 'GET_BUDGET_SUCCESS';
// export const OPEN_VIEW_BUDGET_MODEL = 'OPEN_VIEW_BUDGET_MODEL';
// export const OPEN_VIEW_BUDGET_MODEL_SUCCESS = 'OPEN_VIEW_BUDGET_MODEL_SUCCESS';
// export const CLOSE_VIEW_BUDGET_MODEL = 'CLOSE_VIEW_BUDGET_MODEL';
// export const DELETE_BUDGET = 'DELETE_BUDGET';
// export const OPEN_EDIT_BUDGET_MODEL = 'OPEN_EDIT_BUDGET_MODEL';
// export const OPEN_EDIT_BUDGET_MODEL_SUCCESS = 'OPEN_EDIT_BUDGET_MODEL_SUCCESS';
// //holidays
// export const OPEN_ADD_NEW_HOLIDAYS_MODEL = 'OPEN_ADD_NEW_HOLIDAYS_MODEL';
// export const CLOSE_ADD_NEW_HOLIDAYS_MODEL = 'CLOSE_ADD_NEW_HOLIDAYS_MODEL';
// export const SAVE_HOLIDAYS = 'SAVE_HOLIDAYS';
// export const SAVE_HOLIDAYS_SUCCESS = 'SAVE_HOLIDAYS_SUCCESS';
// export const GET_HOLIDAYS = 'GET_HOLIDAYS';
// export const GET_HOLIDAYS_SUCCESS = 'GET_HOLIDAYS_SUCCESS';
// export const OPEN_VIEW_HOLIDAYS_MODEL = 'OPEN_VIEW_HOLIDAYS_MODEL';
// export const OPEN_VIEW_HOLIDAYS_MODEL_SUCCESS = 'OPEN_VIEW_HOLIDAYS_MODEL_SUCCESS';
// export const CLOSE_VIEW_HOLIDAYS_MODEL = 'CLOSE_VIEW_HOLIDAYS_MODEL';
// export const DELETE_HOLIDAYS = 'DELETE_HOLIDAYS';
// export const OPEN_EDIT_HOLIDAYS_MODEL = 'OPEN_EDIT_HOLIDAYS_MODEL';
// export const OPEN_EDIT_HOLIDAYS_MODEL_SUCCESS = 'OPEN_EDIT_HOLIDAYS_MODEL_SUCCESS';
//
//
// // gym access slot
// export const OPEN_VIEW_GYM_ACCESS_SLOT_MODEL = 'OPEN_VIEW_GYM_ACCESS_SLOT_MODEL';
// export const OPEN_VIEW_GYM_ACCESS_SLOT_MODEL_SUCCESS = 'OPEN_VIEW_GYM_ACCESS_SLOT_MODEL_SUCCESS';
// export const CLOSE_VIEW_GYM_ACCESS_SLOT_MODEL = 'CLOSE_VIEW_GYM_ACCESS_SLOT_MODEL';
// export const DELETE_GYM_ACCESS_SLOT = 'DELETE_GYM_ACCESS_SLOT';
// export const CHANGE_GYM_ACCESS_SLOT = 'CHANGE_GYM_ACCESS_SLOT';
// export const CHANGE_SAVE_MEMBER_GYMACCESSSLOT = 'CHANGE_SAVE_MEMBER_GYMACCESSSLOT';
// export const CHANGE_SAVE_MEMBER_GYMACCESSSLOT_SUCCESS = 'CHANGE_SAVE_MEMBER_GYMACCESSSLOT_SUCCESS';
// export const CHANGE_SAVE_MEMBER_GYMACCESSSLOT_FAILURE = 'CHANGE_SAVE_MEMBER_GYMACCESSSLOT_FAILURE';
//
//
// // Advertisement
// export const OPEN_ADD_NEW_ADVERTISEMENT_MODEL = 'OPEN_ADD_NEW_ADVERTISEMENT_MODEL';
// export const CLOSE_ADD_NEW_ADVERTISEMENT_MODEL = 'CLOSE_ADD_NEW_ADVERTISEMENT_MODEL';
// export const SAVE_ADVERTISEMENT = 'SAVE_ADVERTISEMENT';
// export const SAVE_ADVERTISEMENT_SUCCESS = 'SAVE_ADVERTISEMENT_SUCCESS';
// export const GET_ADVERTISEMENTS = 'GET_ADVERTISEMENTS';
// export const GET_ADVERTISEMENTS_SUCCESS = 'GET_ADVERTISEMENTS_SUCCESS';
// export const OPEN_VIEW_ADVERTISEMENT_MODEL = 'OPEN_VIEW_ADVERTISEMENT_MODEL';
// export const OPEN_VIEW_ADVERTISEMENT_MODEL_SUCCESS = 'OPEN_VIEW_ADVERTISEMENT_MODEL_SUCCESS';
// export const CLOSE_VIEW_ADVERTISEMENT_MODEL = 'CLOSE_VIEW_ADVERTISEMENT_MODEL';
// export const OPEN_EDIT_ADVERTISEMENT_MODEL = 'OPEN_EDIT_ADVERTISEMENT_MODEL';
// export const OPEN_EDIT_ADVERTISEMENT_MODEL_SUCCESS = 'OPEN_EDIT_ADVERTISEMENT_MODEL_SUCCESS';
// export const DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT';
//
// export const ADVERTISEMENT_HANDLE_CHANGE_SELECT_ALL = 'ADVERTISEMENT_HANDLE_CHANGE_SELECT_ALL';
// export const ADVERTISEMENT_HANDLE_SINGLE_CHECKBOX_CHANGE = 'ADVERTISEMENT_HANDLE_SINGLE_CHECKBOX_CHANGE';
// export const OPEN_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL = 'OPEN_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL';
// export const CLOSE_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL = 'CLOSE_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL';
// export const OPEN_DISABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL = 'OPEN_DISABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL';
// export const CLOSE_DISABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL = 'CLOSE_DISABLEPUBLISHINGSTATUS_ADVERTISEMENT_MODEL';
// export const SAVE_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT = 'SAVE_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT';
// export const SAVE_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT_SUCCESS = 'SAVE_ENABLEPUBLISHINGSTATUS_ADVERTISEMENT_SUCCESS';
//
//
// // Result And Testimonial
// export const OPEN_ADD_NEW_RESULTANDTESTIMONIAL_MODEL = 'OPEN_ADD_NEW_RESULTANDTESTIMONIAL_MODEL';
// export const OPEN_ADD_NEW_RESULTANDTESTIMONIAL_MODEL_SUCCESS = 'OPEN_ADD_NEW_RESULTANDTESTIMONIAL_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_RESULTANDTESTIMONIAL_MODEL = 'CLOSE_ADD_NEW_RESULTANDTESTIMONIAL_MODEL';
// export const SAVE_RESULTANDTESTIMONIAL = 'SAVE_RESULTANDTESTIMONIAL';
// export const SAVE_RESULTANDTESTIMONIAL_SUCCESS = 'SAVE_RESULTANDTESTIMONIAL_SUCCESS';
// export const GET_RESULTANDTESTIMONIAL = 'GET_RESULTANDTESTIMONIAL';
// export const GET_RESULTANDTESTIMONIAL_SUCCESS = 'GET_RESULTANDTESTIMONIAL_SUCCESS';
// export const OPEN_VIEW_RESULTANDTESTIMONIAL_MODEL = 'OPEN_VIEW_RESULTANDTESTIMONIAL_MODEL';
// export const OPEN_VIEW_RESULTANDTESTIMONIAL_MODEL_SUCCESS = 'OPEN_VIEW_RESULTANDTESTIMONIAL_MODEL_SUCCESS';
// export const CLOSE_VIEW_RESULTANDTESTIMONIAL_MODEL = 'CLOSE_VIEW_RESULTANDTESTIMONIAL_MODEL';
// export const OPEN_EDIT_RESULTANDTESTIMONIAL_MODEL = 'OPEN_EDIT_RESULTANDTESTIMONIAL_MODEL';
// export const OPEN_EDIT_RESULTANDTESTIMONIAL_MODEL_SUCCESS = 'OPEN_EDIT_RESULTANDTESTIMONIAL_MODEL_SUCCESS';
// export const DELETE_RESULTANDTESTIMONIAL = 'DELETE_RESULTANDTESTIMONIAL';
//
// export const RESULTANDTESTIMONIAL_HANDLE_CHANGE_SELECT_ALL = 'RESULTANDTESTIMONIAL_HANDLE_CHANGE_SELECT_ALL';
// export const RESULTANDTESTIMONIAL_HANDLE_SINGLE_CHECKBOX_CHANGE = 'RESULTANDTESTIMONIAL_HANDLE_SINGLE_CHECKBOX_CHANGE';
// export const OPEN_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL = 'OPEN_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL';
// export const CLOSE_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL = 'CLOSE_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL';
// export const OPEN_DISABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL = 'OPEN_DISABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL';
// export const CLOSE_DISABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL = 'CLOSE_DISABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_MODEL';
// export const SAVE_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL = 'SAVE_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL';
// export const SAVE_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_SUCCESS = 'SAVE_ENABLEPUBLISHINGSTATUS_RESULTANDTESTIMONIAL_SUCCESS';
//
//
// // Poster
// export const OPEN_ADD_NEW_POSTER_MODEL = 'OPEN_ADD_NEW_POSTER_MODEL';
// export const CLOSE_ADD_NEW_POSTER_MODEL = 'CLOSE_ADD_NEW_POSTER_MODEL';
// export const SAVE_POSTER = 'SAVE_POSTER';
// export const SAVE_POSTER_SUCCESS = 'SAVE_POSTER_SUCCESS';
// export const GET_POSTER = 'GET_POSTER';
// export const GET_POSTER_SUCCESS = 'GET_POSTER_SUCCESS';
// export const DELETE_POSTER = 'DELETE_POSTER';
//
//
// // Manage Shift
// export const OPEN_ADD_NEW_SHIFT_MODEL = 'OPEN_ADD_NEW_SHIFT_MODEL';
// export const CLOSE_ADD_NEW_SHIFT_MODEL = 'CLOSE_ADD_NEW_SHIFT_MODEL';
// export const GET_SHIFT = 'GET_SHIFT';
// export const GET_SHIFT_SUCCESS = 'GET_SHIFT_SUCCESS';
// export const OPEN_EDIT_SHIFT_MODEL = 'OPEN_EDIT_SHIFT_MODEL';
// export const OPEN_EDIT_SHIFT_MODEL_SUCCESS = 'OPEN_EDIT_SHIFT_MODEL_SUCCESS';
// export const DELETE_SHIFT = 'DELETE_SHIFT';
// export const SAVE_SHIFT_CONFIGURATION = 'SAVE_SHIFT_CONFIGURATION';
// export const SAVE_SHIFT_CONFIGURATION_SUCCESS = 'SAVE_SHIFT_CONFIGURATION_SUCCESS';
//
//
// // Assign Shift
// export const OPEN_ADD_NEW_ASSIGNSHIFT_MODEL = 'OPEN_ADD_NEW_ASSIGNSHIFT_MODEL';
// export const OPEN_ADD_NEW_ASSIGNSHIFT_MODEL_SUCCESS = 'OPEN_ADD_NEW_ASSIGNSHIFT_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_ASSIGNSHIFT_MODEL = 'CLOSE_ADD_NEW_ASSIGNSHIFT_MODEL';
// export const GET_ASSIGNSHIFT = 'GET_ASSIGNSHIFT';
// export const GET_ASSIGNSHIFT_SUCCESS = 'GET_ASSIGNSHIFT_SUCCESS';
// export const OPEN_EDIT_ASSIGNSHIFT_MODEL = 'OPEN_EDIT_ASSIGNSHIFT_MODEL';
// export const OPEN_EDIT_ASSIGNSHIFT_MODEL_SUCCESS = 'OPEN_EDIT_ASSIGNSHIFT_MODEL_SUCCESS';
// export const DELETE_ASSIGNSHIFT = 'DELETE_ASSIGNSHIFT';
// export const SAVE_ASSIGNSHIFT = 'SAVE_ASSIGNSHIFT';
// export const SAVE_ASSIGNSHIFT_SUCCESS = 'SAVE_ASSIGNSHIFT_SUCCESS';
//
//
// // member signup Detail
// export const SAVE_MEMBER_SIGNUPDETAIL = 'SAVE_MEMBER_SIGNUPDETAIL';
// export const SAVE_MEMBER_SIGNUPDETAIL_SUCCESS = 'SAVE_MEMBER_SIGNUPDETAIL_SUCCESS';
// export const OPEN_ADD_NEW_EMAILVERIFICATION_MODEL = 'OPEN_ADD_NEW_EMAILVERIFICATION_MODEL';
// export const OPEN_ADD_NEW_EMAILVERIFICATION_MODEL_SUCCESS = 'OPEN_ADD_NEW_EMAILVERIFICATION_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_EMAILVERIFICATION_MODEL = 'CLOSE_ADD_NEW_EMAILVERIFICATION_MODEL';
// export const SAVE_VERIFICATIONCODE = 'SAVE_VERIFICATIONCODE';
//
//
// // master Dashboard
//
// export const GET_MASTERDASHBOARD_TODAYENQUIRYREMINDER = 'GET_MASTERDASHBOARD_TODAYENQUIRYREMINDER';
// export const GET_MASTERDASHBOARD_TODAYENQUIRYREMINDER_SUCCESS = 'GET_MASTERDASHBOARD_TODAYENQUIRYREMINDER_SUCCESS';
//
// export const GET_MASTERDASHBOARD_TODAYMEMBERREMINDER = 'GET_MASTERDASHBOARD_TODAYMEMBERREMINDER';
// export const GET_MASTERDASHBOARD_TODAYMEMBERREMINDER_SUCCESS = 'GET_MASTERDASHBOARD_TODAYMEMBERREMINDER_SUCCESS';
//
//
// // followupDashboard
//
// export const GET_FOLLOWUPDASHBOARD_ONTRIALENQUIRIES = 'GET_FOLLOWUPDASHBOARD_ONTRIALENQUIRIES';
// export const GET_FOLLOWUPDASHBOARD_ONTRIALENQUIRIES_SUCCESS = 'GET_FOLLOWUPDASHBOARD_ONTRIALENQUIRIES_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_RECENTENQUIRIES = 'GET_FOLLOWUPDASHBOARD_RECENTENQUIRIES';
// export const GET_FOLLOWUPDASHBOARD_RECENTENQUIRIES_SUCCESS = 'GET_FOLLOWUPDASHBOARD_RECENTENQUIRIES_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_RECENTEXPIREDMEMBER = 'GET_FOLLOWUPDASHBOARD_RECENTEXPIREDMEMBER';
// export const GET_FOLLOWUPDASHBOARD_RECENTEXPIREDMEMBER_SUCCESS = 'GET_FOLLOWUPDASHBOARD_RECENTEXPIREDMEMBER_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_MEMBERSHIPTOBEEXPIRED = 'GET_FOLLOWUPDASHBOARD_MEMBERSHIPTOBEEXPIRED';
// export const GET_FOLLOWUPDASHBOARD_MEMBERSHIPTOBEEXPIRED_SUCCESS = 'GET_FOLLOWUPDASHBOARD_MEMBERSHIPTOBEEXPIRED_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_PAYMENTDUES = 'GET_FOLLOWUPDASHBOARD_PAYMENTDUES';
// export const GET_FOLLOWUPDASHBOARD_PAYMENTDUES_SUCCESS = 'GET_FOLLOWUPDASHBOARD_PAYMENTDUES_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_RECENTPTEXPIRED = 'GET_FOLLOWUPDASHBOARD_RECENTPTEXPIRED';
// export const GET_FOLLOWUPDASHBOARD_RECENTPTEXPIRED_SUCCESS = 'GET_FOLLOWUPDASHBOARD_RECENTPTEXPIRED_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_PTTOBEEXPIRED = 'GET_FOLLOWUPDASHBOARD_PTTOBEEXPIRED';
// export const GET_FOLLOWUPDASHBOARD_PTTOBEEXPIRED_SUCCESS = 'GET_FOLLOWUPDASHBOARD_PTTOBEEXPIRED_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_MISSEDENQUIRYFOLLOWUP = 'GET_FOLLOWUPDASHBOARD_MISSEDENQUIRYFOLLOWUP';
// export const GET_FOLLOWUPDASHBOARD_MISSEDENQUIRYFOLLOWUP_SUCCESS = 'GET_FOLLOWUPDASHBOARD_MISSEDENQUIRYFOLLOWUP_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_MISSEDMEMBERFOLLOWUP = 'GET_FOLLOWUPDASHBOARD_MISSEDMEMBERFOLLOWUP';
// export const GET_FOLLOWUPDASHBOARD_MISSEDMEMBERFOLLOWUP_SUCCESS = 'GET_FOLLOWUPDASHBOARD_MISSEDMEMBERFOLLOWUP_SUCCESS';
//
//
//
// //package module
// export const OPEN_ADD_NEW_PACKAGE_MODEL = 'OPEN_ADD_NEW_PACKAGE_MODEL';
// export const OPEN_ADD_NEW_PACKAGE_MODEL_SUCCESS = 'OPEN_ADD_NEW_PACKAGE_MODEL_SUCCESS';
// export const CLOSE_ADD_NEW_PACKAGE_MODEL = 'CLOSE_ADD_NEW_PACKAGE_MODEL';
// export const SAVE_PACKAGE = 'SAVE_PACKAGE';
// export const SAVE_PACKAGE_SUCCESS = 'SAVE_PACKAGE_SUCCESS';
// export const GET_PACKAGES = 'GET_PACKAGES';
// export const GET_PACKAGES_SUCCESS = 'GET_PACKAGES_SUCCESS';
// export const OPEN_VIEW_PACKAGE_MODEL = 'OPEN_VIEW_PACKAGE_MODEL';
// export const OPEN_VIEW_PACKAGE_MODEL_SUCCESS = 'OPEN_VIEW_PACKAGE_MODEL_SUCCESS';
// export const CLOSE_VIEW_PACKAGE_MODEL = 'CLOSE_VIEW_PACKAGE_MODEL';
// export const OPEN_EDIT_PACKAGE_MODEL = 'OPEN_EDIT_PACKAGE_MODEL';
// export const OPEN_EDIT_PACKAGE_MODEL_SUCCESS = 'OPEN_EDIT_PACKAGE_MODEL_SUCCESS';
// export const DELETE_PACKAGE = 'DELETE_PACKAGE';
//
//
// export const GET_FOLLOWUPDASHBOARD_RECENTMEMBER = 'GET_FOLLOWUPDASHBOARD_RECENTMEMBER';
// export const GET_FOLLOWUPDASHBOARD_RECENTMEMBER_SUCCESS = 'GET_FOLLOWUPDASHBOARD_RECENTMEMBER_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_TODAY_BIRTHDAY = 'GET_FOLLOWUPDASHBOARD_TODAY_BIRTHDAY';
// export const GET_FOLLOWUPDASHBOARD_TODAY_BIRTHDAY_SUCCESS = 'GET_FOLLOWUPDASHBOARD_TODAY_BIRTHDAY_SUCCESS';
//
// export const GET_FOLLOWUPDASHBOARD_TODAY_ANNIVERSARY = 'GET_FOLLOWUPDASHBOARD_TODAY_ANNIVERSARY';
// export const GET_FOLLOWUPDASHBOARD_TODAY_ANNIVERSARY_SUCCESS = 'GET_FOLLOWUPDASHBOARD_TODAY_ANNIVERSARY_SUCCESS';
//
//
// // induction checklist
// export const GET_INDUCTION_CHECKLIST_MEMBERS = 'GET_INDUCTION_CHECKLIST_MEMBERS';
// export const GET_INDUCTION_CHECKLIST_MEMBERS_SUCCESS = 'GET_INDUCTION_CHECKLIST_MEMBERS_SUCCESS';
//
//
// //loginpageenquiryform
//
// export const SAVE_LOGIN_ENQUIRY_FORM = 'SAVE_ENQUIRY_FORM';
// export const SAVE_LOGIN_ENQUIRY_FORM_SUCCESS = 'SAVE_ENQUIRY_FORM_SUCCESS';
// export const OPEN_LOGIN_ENQUIRY_FORM = 'OPEN_LOGIN_ENQUIRY_FORM';
// export const CLOSE_LOGIN_ENQUIRY_FORM = 'CLOSE_LOGIN_ENQUIRY_FORM';
// export const TOGGLE_THEME_PANEL = 'TOGGLE_THEME_PANEL';
